// Comprehensive catalog of 22 After Effects effect categories and all 200+ built-in effects.
// Each effect provides parameter mappings, hints, group, and tags for instant search & FX Console.

import { RENDERED_EFFECTS } from './effectSupport';
export type EffectDefinition = {
  id: string;
  label: string;
  group: EffectCategory;
  hint: string;
  apply: Record<string, number | boolean>;
  tags?: string[];
  isTransition?: boolean;
  isAudio?: boolean;
};

export type EffectCategory =
  | '3D Channel'
  | 'Audio'
  | 'Blur & Sharpen'
  | 'Planar Tracking'
  | 'Channel'
  | 'Color Correction'
  | 'Distort'
  | 'Expression Controls'
  | 'Generate'
  | 'Immersive Video / VR'
  | 'Keying'
  | 'Matte'
  | 'Noise & Grain'
  | 'Perspective'
  | 'Simulation / Particles'
  | 'Stylize'
  | 'Text'
  | 'Time'
  | 'Transition'
  | 'Utility'
  | 'Obsolete / Legacy';

export const EFFECT_CATEGORIES: EffectCategory[] = [
  '3D Channel',
  'Audio',
  'Blur & Sharpen',
  'Planar Tracking',
  'Channel',
  'Color Correction',
  'Distort',
  'Expression Controls',
  'Generate',
  'Immersive Video / VR',
  'Keying',
  'Matte',
  'Noise & Grain',
  'Perspective',
  'Simulation / Particles',
  'Stylize',
  'Text',
  'Time',
  'Transition',
  'Utility',
  'Obsolete / Legacy',
];

export const ALL_EFFECTS: EffectDefinition[] = [
  // ── 3D Channel ─────────────────────────────────────────────────────────────
  { id: '3d-channel-extract', label: '3D Channel Extract', group: '3D Channel', hint: 'Extracts depth/aux channels from 3D renders', apply: { contrast: 15 }, tags: ['depth', 'zbuffer', 'render'] },
  { id: 'cryptomatte', label: 'Cryptomatte', group: '3D Channel', hint: 'Extracts ID mattes generated by renderers like Arnold/Redshift', apply: { contrast: 10 }, tags: ['matte', 'id', 'isolate'] },
  { id: 'depth-matte', label: 'Depth Matte', group: '3D Channel', hint: 'Isolates objects along the Z-depth axis', apply: { contrast: 20 }, tags: ['depth', 'zspace', 'mask'] },
  { id: 'depth-of-field', label: 'Depth of Field', group: '3D Channel', hint: 'Simulates camera focal blur using depth map', apply: { blur: 14 }, tags: ['dof', 'lens', 'blur', 'bokeh'] },
  { id: 'extractor', label: 'Extractor', group: '3D Channel', hint: 'Extracts OpenEXR auxiliary channels', apply: {}, tags: ['exr', 'channels', 'openexr'] },
  { id: 'fog-3d', label: 'Fog 3D', group: '3D Channel', hint: 'Simulates atmospheric depth fog based on Z distance', apply: { brightness: 12, contrast: -10 }, tags: ['atmosphere', 'depth', 'haze'] },
  { id: 'id-matte', label: 'ID Matte', group: '3D Channel', hint: 'Isolates elements via auxiliary object ID tags', apply: {}, tags: ['id', 'object', 'mask'] },
  { id: 'identifier', label: 'IDentifier', group: '3D Channel', hint: 'Inspects and selects material/object IDs in 3D files', apply: {}, tags: ['id', 'inspect', 'channels'] },

  // ── Audio ──────────────────────────────────────────────────────────────────
  { id: 'audio-backwards', label: 'Backwards', group: 'Audio', hint: 'Plays audio track in reverse', apply: { reverse: true }, isAudio: true, tags: ['reverse', 'rewind'] },
  { id: 'audio-bass-treble', label: 'Bass & Treble', group: 'Audio', hint: 'Boosts or cuts low and high frequency shelves', apply: { volume: 1 }, isAudio: true, tags: ['eq', 'tone', 'bass', 'treble'] },
  { id: 'audio-delay', label: 'Delay', group: 'Audio', hint: 'Adds echo repeats with feedback and time delay', apply: {}, isAudio: true, tags: ['echo', 'repeat', 'delay'] },
  { id: 'audio-flange-chorus', label: 'Flange & Chorus', group: 'Audio', hint: 'Double tracking, swirling modulations and pitch shifts', apply: {}, isAudio: true, tags: ['flanger', 'chorus', 'modulation'] },
  { id: 'audio-high-low-pass', label: 'High-Low Pass', group: 'Audio', hint: 'Cuts frequencies above or below cutoff points', apply: {}, isAudio: true, tags: ['filter', 'lowpass', 'highpass'] },
  { id: 'audio-modulator', label: 'Modulator', group: 'Audio', hint: 'Frequency and amplitude ring/vibrato modulation', apply: {}, isAudio: true, tags: ['tremolo', 'vibrato', 'ring'] },
  { id: 'audio-parametric-eq', label: 'Parametric EQ', group: 'Audio', hint: 'Multi-band parametric equalizer for precise tuning', apply: {}, isAudio: true, tags: ['eq', 'frequencies', 'curve'] },
  { id: 'audio-reverb', label: 'Reverb', group: 'Audio', hint: 'Simulates room acoustics, halls and ambient reflections', apply: {}, isAudio: true, tags: ['room', 'hall', 'space', 'ambience'] },
  { id: 'audio-stereo-mixer', label: 'Stereo Mixer', group: 'Audio', hint: 'Pan and blend left and right stereo channels', apply: {}, isAudio: true, tags: ['stereo', 'pan', 'balance'] },
  { id: 'audio-tone', label: 'Tone', group: 'Audio', hint: 'Generates sine, square or noise tone frequencies', apply: {}, isAudio: true, tags: ['generator', 'sine', 'beep'] },

  // ── Blur & Sharpen ─────────────────────────────────────────────────────────
  { id: 'bilateral-blur', label: 'Bilateral Blur', group: 'Blur & Sharpen', hint: 'Edge-preserving smart surface smoothing blur', apply: { blur: 8 }, tags: ['smooth', 'skin', 'denoise'] },
  { id: 'camera-lens-blur', label: 'Camera Lens Blur', group: 'Blur & Sharpen', hint: 'Realistic optical bokeh and lens iris distortion', apply: { blur: 16 }, tags: ['bokeh', 'lens', 'dof', 'aperture'] },
  { id: 'camera-shake-deblur', label: 'Camera-Shake Deblur', group: 'Blur & Sharpen', hint: 'Reduces unwanted motion blur from handshake', apply: { contrast: 15 }, tags: ['deblur', 'sharpen', 'shake'] },
  { id: 'cc-cross-blur', label: 'Cross Blur', group: 'Blur & Sharpen', hint: 'Simultaneous horizontal and vertical streak blur', apply: { blur: 10 }, tags: ['streak', 'cross', 'h/v'] },
  { id: 'cc-radial-blur', label: 'Radial Blur', group: 'Blur & Sharpen', hint: 'Rotational spin or zoom flare blur from center', apply: { blur: 12 }, tags: ['spin', 'zoom', 'circular'] },
  { id: 'cc-radial-fast-blur', label: 'Radial Fast Blur', group: 'Blur & Sharpen', hint: 'High-speed directional zoom rays and light shine', apply: { blur: 15, brightness: 10 }, tags: ['fast', 'rays', 'zoom'] },
  { id: 'cc-vector-blur', label: 'Vector Blur', group: 'Blur & Sharpen', hint: 'Flow-based smearing blur along vector direction maps', apply: { blur: 9 }, tags: ['vector', 'smear', 'liquid'] },
  { id: 'channel-blur', label: 'Channel Blur', group: 'Blur & Sharpen', hint: 'Blurs individual red, green, blue or alpha channels', apply: { blur: 10 }, tags: ['rgb', 'chromatic', 'split'] },
  { id: 'compound-blur', label: 'Compound Blur', group: 'Blur & Sharpen', hint: 'Modulates blur amount using another layer as map', apply: { blur: 14 }, tags: ['map', 'masked', 'gradient'] },
  { id: 'directional-blur', label: 'Directional Blur', group: 'Blur & Sharpen', hint: 'Linear motion blur along a specified angle', apply: { blur: 12 }, tags: ['motion', 'angle', 'speed'] },
  { id: 'fast-box-blur', label: 'Fast Box Blur', group: 'Blur & Sharpen', hint: 'High-performance rapid box blur filter', apply: { blur: 10 }, tags: ['fast', 'box', 'smooth'] },
  { id: 'gaussian-blur', label: 'Gaussian Blur', group: 'Blur & Sharpen', hint: 'Smooth, standard bell-curve Gaussian blur', apply: { blur: 12 }, tags: ['soft', 'smooth', 'defocus'] },
  { id: 'radial-blur', label: 'Radial Blur', group: 'Blur & Sharpen', hint: 'Radial spin or zoom blur around anchor point', apply: { blur: 14 }, tags: ['spin', 'zoom', 'vortex'] },
  { id: 'sharpen', label: 'Sharpen', group: 'Blur & Sharpen', hint: 'Increases edge contrast to accentuate fine details', apply: { contrast: 25 }, tags: ['crisp', 'detail', 'edges'] },
  { id: 'smart-blur', label: 'Smart Blur', group: 'Blur & Sharpen', hint: 'Blurs surfaces while maintaining crisp outline edges', apply: { blur: 8, contrast: 10 }, tags: ['edges', 'cartoon', 'smooth'] },
  { id: 'unsharp-mask', label: 'Unsharp Mask', group: 'Blur & Sharpen', hint: 'Classic high-frequency detail enhancer', apply: { contrast: 30 }, tags: ['clarity', 'pop', 'crisp'] },

  // ── Planar Tracking ─────────────────────────────────────────────────────────
  { id: 'mocha-ae', label: 'Planar Tracker', group: 'Planar Tracking', hint: 'Planar tracking, rotoscoping and camera solve workspace', apply: {}, tags: ['tracking', 'roto', 'planar', 'mask'] },

  // ── Channel ────────────────────────────────────────────────────────────────
  { id: 'arithmetic', label: 'Arithmetic', group: 'Channel', hint: 'Performs mathematical operators on color channels', apply: { contrast: 15 }, tags: ['math', 'add', 'multiply'] },
  { id: 'blend', label: 'Blend', group: 'Channel', hint: 'Blends two layers with adjustable cross-dissolve', apply: {}, tags: ['mix', 'composite'] },
  { id: 'calculations', label: 'Calculations', group: 'Channel', hint: 'Combines channels between two different layers', apply: {}, tags: ['math', 'transfer', 'mode'] },
  { id: 'cc-composite', label: 'Composite', group: 'Channel', hint: 'Composites the original source image back on top', apply: {}, tags: ['original', 'blend', 'source'] },
  { id: 'channel-combiner', label: 'Channel Combiner', group: 'Channel', hint: 'Reroutes channel data (e.g. RGB to HSL or Alpha)', apply: {}, tags: ['reroute', 'convert', 'matrix'] },
  { id: 'compound-arithmetic', label: 'Compound Arithmetic', group: 'Channel', hint: 'Math operations between source and control layer', apply: {}, tags: ['math', 'compound'] },
  { id: 'invert', label: 'Invert', group: 'Channel', hint: 'Inverts color channels to their complementary values', apply: { invert: 100 }, tags: ['negative', 'reverse', 'flip'] },
  { id: 'minimax', label: 'Minimax', group: 'Channel', hint: 'Dilates or erodes color boundaries (maximum/minimum)', apply: { contrast: 20 }, tags: ['dilate', 'erode', 'choke'] },
  { id: 'remove-color-matting', label: 'Remove Color Matting', group: 'Channel', hint: 'Strips black/white premultiplied fringe outlines', apply: {}, tags: ['fringe', 'premultiply', 'clean'] },
  { id: 'set-channels', label: 'Set Channels', group: 'Channel', hint: 'Copies color channels from specified sources', apply: {}, tags: ['copy', 'alpha', 'rgb'] },
  { id: 'set-matte', label: 'Set Matte', group: 'Channel', hint: 'Replaces alpha channel using another layer as mask', apply: {}, tags: ['alpha', 'mask', 'cutout'] },
  { id: 'shift-channels', label: 'Shift Channels', group: 'Channel', hint: 'Swaps RGB and Alpha channels freely', apply: {}, tags: ['swap', 'glitch', 'chroma'] },
  { id: 'solid-composite', label: 'Solid Composite', group: 'Channel', hint: 'Fills transparent areas with a solid background color', apply: {}, tags: ['background', 'alpha', 'solid'] },

  // ── Cinema 4D ──────────────────────────────────────────────────────────────

  // ── Color Correction ───────────────────────────────────────────────────────
  { id: 'auto-color', label: 'Auto Color', group: 'Color Correction', hint: 'Automatically adjusts contrast and color cast balance', apply: { contrast: 15, saturation: 110 }, tags: ['auto', 'balance'] },
  { id: 'auto-contrast', label: 'Auto Contrast', group: 'Color Correction', hint: 'Stretches histogram to full dynamic range', apply: { contrast: 20 }, tags: ['auto', 'histogram'] },
  { id: 'auto-levels', label: 'Auto Levels', group: 'Color Correction', hint: 'Automatically clips black and white points per channel', apply: { contrast: 15, brightness: 5 }, tags: ['auto', 'levels'] },
  { id: 'black-white', label: 'Black & White', group: 'Color Correction', hint: 'Converts color picture into nuanced monochrome black & white', apply: { saturation: 0 }, tags: ['grayscale', 'monochrome', 'bw'] },
  { id: 'brightness-contrast', label: 'Brightness & Contrast', group: 'Color Correction', hint: 'Quick global brightness and contrast tonal curve', apply: { brightness: 15, contrast: 20 }, tags: ['adjust', 'tone'] },
  { id: 'broadcast-colors', label: 'Broadcast Colors', group: 'Color Correction', hint: 'Clamps luminance and chroma to legal broadcast standards', apply: { saturation: 95 }, tags: ['legal', 'broadcast', 'clamp'] },
  { id: 'cc-color-neutralizer', label: 'Color Neutralizer', group: 'Color Correction', hint: 'Neutralizes unwanted color tint casts across tonal ranges', apply: { saturation: 95 }, tags: ['white-balance', 'cast'] },
  { id: 'cc-color-offset', label: 'Color Offset', group: 'Color Correction', hint: 'Offsets RGB color channels independently', apply: { hue: 15 }, tags: ['offset', 'rgb', 'grade'] },
  { id: 'cc-kernel', label: 'Kernel', group: 'Color Correction', hint: 'Custom 3x3 matrix filtering and color convolution', apply: { contrast: 10 }, tags: ['matrix', 'kernel', 'convolution'] },
  { id: 'cc-toner', label: 'Toner', group: 'Color Correction', hint: 'Applies duotone, tritone or pentatone color grading', apply: { hue: 25, saturation: 120 }, tags: ['duotone', 'tritone', 'sepia'] },
  { id: 'change-color', label: 'Change Color', group: 'Color Correction', hint: 'Replaces a specific hue range with another target hue', apply: { hue: 45 }, tags: ['hue', 'swap', 'recolor'] },
  { id: 'change-to-color', label: 'Change to Color', group: 'Color Correction', hint: 'Shifts source color directly to a chosen destination color', apply: { hue: 90 }, tags: ['swap', 'destination', 'tint'] },
  { id: 'channel-mixer', label: 'Channel Mixer', group: 'Color Correction', hint: 'Mixes red, green and blue channels for custom looks', apply: { contrast: 10 }, tags: ['mixer', 'matrix', 'cross'] },
  { id: 'color-balance', label: 'Color Balance', group: 'Color Correction', hint: 'Adjusts RGB amounts in shadows, midtones, and highlights', apply: { contrast: 12, brightness: 5 }, tags: ['shadows', 'midtones', 'highlights'] },
  { id: 'color-balance-hls', label: 'Color Balance (HLS)', group: 'Color Correction', hint: 'Adjusts hue, lightness, and saturation directly', apply: { saturation: 125, hue: 10 }, tags: ['hls', 'lightness', 'saturation'] },
  { id: 'color-link', label: 'Color Link', group: 'Color Correction', hint: 'Samples color from another layer to match grades', apply: {}, tags: ['match', 'sample', 'grade'] },
  { id: 'color-stabilizer', label: 'Color Stabilizer', group: 'Color Correction', hint: 'Removes flicker by stabilizing reference pixel brightness', apply: {}, tags: ['flicker', 'deflicker', 'stable'] },
  { id: 'colorama', label: 'Colorama', group: 'Color Correction', hint: 'Maps luminance values to vibrant psychedelic color wheels', apply: { hue: 60, saturation: 180 }, tags: ['psychedelic', 'gradient', 'palette'] },
  { id: 'curves', label: 'Curves', group: 'Color Correction', hint: 'Precise spline curve grading for RGB and individual channels', apply: { contrast: 25, brightness: 5 }, tags: ['spline', 's-curve', 'contrast'] },
  { id: 'equalize', label: 'Equalize', group: 'Color Correction', hint: 'Equalizes brightness spectrum to maximize contrast', apply: { contrast: 35 }, tags: ['histogram', 'boost'] },
  { id: 'exposure', label: 'Exposure', group: 'Color Correction', hint: 'Photographic F-stop exposure and gamma offset compensation', apply: { brightness: 25, contrast: 10 }, tags: ['stops', 'iso', 'f-stop'] },
  { id: 'gamma-pedestal-gain', label: 'Gamma/Pedestal/Gain', group: 'Color Correction', hint: 'Broadcast lift, gamma, and gain three-way controls', apply: { brightness: 5, contrast: 15 }, tags: ['lift', 'gamma', 'gain'] },
  { id: 'hue-saturation', label: 'Hue/Saturation', group: 'Color Correction', hint: 'Rotate entire color spectrum and adjust vibrancy', apply: { hue: 20, saturation: 130 }, tags: ['vibrant', 'recolor', 'boost'] },
  { id: 'leave-color', label: 'Leave Color', group: 'Color Correction', hint: 'Desaturates everything except one chosen accent color (Sin City)', apply: { saturation: 35 }, tags: ['isolation', 'pop', 'selective'] },
  { id: 'levels', label: 'Levels', group: 'Color Correction', hint: 'Black point, white point, and midtone gamma sliders', apply: { contrast: 20, brightness: 5 }, tags: ['histogram', 'blackpoint', 'gamma'] },
  { id: 'levels-individual-controls', label: 'Levels (Individual Controls)', group: 'Color Correction', hint: 'Individual RGBA levels sliders for animatable keyframes', apply: { contrast: 20 }, tags: ['keyframes', 'per-channel'] },
  { id: 'lumetri-color', label: 'Helios Color Studio', group: 'Color Correction', hint: 'Professional cinema grading: Basic, Creative, Curves, Color Wheels & Vignette', apply: { brightness: 5, contrast: 15, saturation: 115 }, tags: ['cinema', 'film', 'grade', 'wheels', 'vignette'] },
  { id: 'photo-filter', label: 'Photo Filter', group: 'Color Correction', hint: 'Warming, cooling, and optical photographic lens filters', apply: { hue: 15, saturation: 110 }, tags: ['warming', 'cooling', 'lens'] },
  { id: 'ps-arbitrary-map', label: 'PS Arbitrary Map', group: 'Color Correction', hint: 'Loads Photoshop arbitrary color mapping curves', apply: {}, tags: ['photoshop', 'curve', 'lut'] },
  { id: 'selective-color', label: 'Selective Color', group: 'Color Correction', hint: 'CMYK selective color grading on individual color ranges', apply: { saturation: 110 }, tags: ['cmyk', 'selective', 'print'] },
  { id: 'shadow-highlight', label: 'Shadow/Highlight', group: 'Color Correction', hint: 'Recovers underexposed shadows and blown-out highlights', apply: { brightness: 10, contrast: -10 }, tags: ['hdr', 'recover', 'shadows'] },
  { id: 'tint', label: 'Tint', group: 'Color Correction', hint: 'Maps black and white to two chosen custom colors', apply: { saturation: 20, contrast: 20 }, tags: ['duotone', 'recolor', 'tone'] },
  { id: 'tritone', label: 'Tritone', group: 'Color Correction', hint: 'Three-color tonal mapping across shadows, midtones and highlights', apply: { saturation: 40, contrast: 15 }, tags: ['sepia', 'duotone', 'grade'] },
  { id: 'vibrance', label: 'Vibrance', group: 'Color Correction', hint: 'Smart saturation boost protecting skin tones and already-saturated hues', apply: { saturation: 135 }, tags: ['smart', 'skin', 'color'] },
  { id: 'video-limiter', label: 'Video Limiter', group: 'Color Correction', hint: 'Restricts video signals to legal EBU / ITU broadcast tolerances', apply: {}, tags: ['legal', 'ebu', 'safe'] },

  // ── Distort ────────────────────────────────────────────────────────────────
  { id: 'bezier-warp', label: 'Bezier Warp', group: 'Distort', hint: 'Multi-point bezier grid mesh for organic warping', apply: {}, tags: ['warp', 'bezier', 'bend'] },
  { id: 'bulge', label: 'Bulge', group: 'Distort', hint: 'Magnifies or pinches picture within an elliptical lens area', apply: {}, tags: ['pinch', 'lens', 'bubble'] },
  { id: 'cc-bend-it', label: 'Bend It', group: 'Distort', hint: 'Bends an image along a two-point line segment', apply: {}, tags: ['bend', 'flex', 'curve'] },
  { id: 'cc-bender', label: 'Bender', group: 'Distort', hint: 'Arcs or curves layer between two pivot handles', apply: {}, tags: ['arc', 'bend', 'warp'] },
  { id: 'cc-blobbylize', label: 'Blobbylize', group: 'Distort', hint: 'Gives layers a melted molten liquid glass look', apply: { contrast: 15 }, tags: ['liquid', 'melt', 'slime'] },
  { id: 'cc-flo-motion', label: 'Flo Motion', group: 'Distort', hint: 'Two-pin magnetic liquid vortex distortion', apply: {}, tags: ['vortex', 'pull', 'flow'] },
  { id: 'cc-griddler', label: 'Griddler', group: 'Distort', hint: 'Divides layer into a grid of animated floating tiles', apply: {}, tags: ['grid', 'tiles', 'matrix'] },
  { id: 'cc-lens', label: 'Lens', group: 'Distort', hint: 'Simulates viewing layer through a fisheye spherical lens', apply: {}, tags: ['fisheye', 'sphere', 'lens'] },
  { id: 'cc-page-turn', label: 'Page Turn', group: 'Distort', hint: 'Simulates a book or magazine page peeling corner peel', apply: {}, tags: ['peel', 'page', 'book'] },
  { id: 'cc-power-pin', label: 'Power Pin', group: 'Distort', hint: 'Enhanced 4-corner perspective pinning with expansion', apply: {}, tags: ['corner', 'pin', 'perspective'] },
  { id: 'cc-ripple-pulse', label: 'Ripple Pulse', group: 'Distort', hint: 'Radiates concentric circular water ripple shockwaves', apply: {}, tags: ['water', 'wave', 'shockwave'] },
  { id: 'cc-slant', label: 'Slant', group: 'Distort', hint: 'Slants and shears picture along horizontal/vertical axes', apply: {}, tags: ['shear', 'italic', 'skew'] },
  { id: 'cc-smear', label: 'Smear', group: 'Distort', hint: 'Pulls and stretches areas between two interactive points', apply: {}, tags: ['stretch', 'pull', 'smudge'] },
  { id: 'cc-split', label: 'Split', group: 'Distort', hint: 'Splits picture open along an expanding tear seam', apply: {}, tags: ['cut', 'tear', 'open'] },
  { id: 'cc-split-2', label: 'Split 2', group: 'Distort', hint: 'Secondary multi-split distortion cutter', apply: {}, tags: ['split', 'cut'] },
  { id: 'cc-tiler', label: 'Tiler', group: 'Distort', hint: 'Tiles and repeats layer infinitely across boundaries', apply: {}, tags: ['repeat', 'tile', 'wallpaper'] },
  { id: 'corner-pin', label: 'Corner Pin', group: 'Distort', hint: 'Four corner positioning for surface screen replacement', apply: {}, tags: ['screen', 'mockup', 'perspective'] },
  { id: 'detail-preserving-upscale', label: 'Detail-preserving Upscale', group: 'Distort', hint: 'Smart AI-like detail preserving frame upscaling', apply: { contrast: 15 }, tags: ['super-res', 'upscale', 'sharp'] },
  { id: 'displacement-map', label: 'Displacement Map', group: 'Distort', hint: 'Displaces pixels horizontally/vertically using a map layer', apply: {}, tags: ['glitch', 'refraction', 'map'] },
  { id: 'liquify', label: 'Liquify', group: 'Distort', hint: 'Interactive brush pushes, twists, shrinks and reconstructs pixels', apply: {}, tags: ['warp', 'brush', 'sculpt'] },
  { id: 'magnify', label: 'Magnify', group: 'Distort', hint: 'Circular or square magnifying glass lens inspection', apply: {}, tags: ['zoom', 'loupe', 'lens'] },
  { id: 'mesh-warp', label: 'Mesh Warp', group: 'Distort', hint: 'Distorts image using an adjustable intersecting wireframe mesh', apply: {}, tags: ['grid', 'mesh', 'sculpt'] },
  { id: 'mirror', label: 'Mirror', group: 'Distort', hint: 'Mirrors an image across a defined symmetry reflection line', apply: { flipH: true }, tags: ['kaleidoscope', 'symmetry', 'reflect'] },
  { id: 'offset', label: 'Offset', group: 'Distort', hint: 'Wraps and pans picture infinitely within frame boundaries', apply: {}, tags: ['wrap', 'pan', 'roll'] },
  { id: 'optics-compensation', label: 'Optics Compensation', group: 'Distort', hint: 'Corrects or adds wide-angle camera lens barrel distortion', apply: {}, tags: ['fisheye', 'gopro', 'lens'] },
  { id: 'polar-coordinates', label: 'Polar Coordinates', group: 'Distort', hint: 'Converts Cartesian (Rectangular) to Polar coordinates (circle)', apply: {}, tags: ['planet', 'donut', 'circle'] },
  { id: 'reshape', label: 'Reshape', group: 'Distort', hint: 'Morphs one mask boundary into another mask boundary', apply: {}, tags: ['morph', 'mask'] },
  { id: 'ripple', label: 'Ripple', group: 'Distort', hint: 'Undulating water ripples radiating outward from origin', apply: {}, tags: ['water', 'pond', 'undulate'] },
  { id: 'rolling-shutter-repair', label: 'Rolling Shutter Repair', group: 'Distort', hint: 'Fixes CMOS sensor rolling shutter wobble and jello artifact', apply: {}, tags: ['jello', 'drone', 'stabilize'] },
  { id: 'smear', label: 'Smear', group: 'Distort', hint: 'Smears pixels along a motion vector stroke', apply: {}, tags: ['motion', 'smudge'] },
  { id: 'spherize', label: 'Spherize', group: 'Distort', hint: 'Wraps picture onto a 3D spherical bubble bulge', apply: {}, tags: ['globe', 'sphere', 'ball'] },
  { id: 'transform', label: 'Transform', group: 'Distort', hint: 'Independent position, anchor, scale, skew, and opacity engine', apply: {}, tags: ['scale', 'rotate', 'skew'] },
  { id: 'turbulent-displace', label: 'Turbulent Displace', group: 'Distort', hint: 'Smooth chaotic turbulence displacement (fire, water, heat)', apply: {}, tags: ['heat', 'smoke', 'organic', 'fire'] },
  { id: 'twirl', label: 'Twirl', group: 'Distort', hint: 'Rotates and twists pixels into a spiral vortex funnel', apply: {}, tags: ['spiral', 'vortex', 'twist'] },
  { id: 'warp', label: 'Warp', group: 'Distort', hint: 'Classic envelope warps: Arc, Fish, Flag, Wave, Twist', apply: {}, tags: ['arc', 'flag', 'wave', 'banner'] },
  { id: 'warp-stabilizer', label: 'Warp Stabilizer', group: 'Distort', hint: 'Automatic point-tracking smooth camera motion stabilizer', apply: {}, tags: ['smooth', 'gimbal', 'camera'] },
  { id: 'wave-warp', label: 'Wave Warp', group: 'Distort', hint: 'Animated sine, square, or triangle waves across layer', apply: {}, tags: ['flag', 'sine', 'water'] },

  // ── Expression Controls ────────────────────────────────────────────────────
  { id: '3d-point-control', label: '3D Point Control', group: 'Expression Controls', hint: 'XYZ 3D coordinate vector driver for expressions', apply: {}, tags: ['xyz', 'point', '3d', 'code'] },
  { id: 'angle-control', label: 'Angle Control', group: 'Expression Controls', hint: 'Dial control to drive rotation angles in expressions', apply: {}, tags: ['dial', 'rotation', 'angle'] },
  { id: 'checkbox-control', label: 'Checkbox Control', group: 'Expression Controls', hint: 'Boolean ON/OFF toggle switch for expression logic', apply: {}, tags: ['boolean', 'toggle', 'switch'] },
  { id: 'color-control', label: 'Color Control', group: 'Expression Controls', hint: 'Color swatch picker to drive global theme colors', apply: {}, tags: ['palette', 'swatch', 'global'] },
  { id: 'dropdown-menu-control', label: 'Dropdown Menu Control', group: 'Expression Controls', hint: 'Dropdown select menu to drive variant modes in expressions', apply: {}, tags: ['select', 'variants', 'menu'] },
  { id: 'layer-control', label: 'Layer Control', group: 'Expression Controls', hint: 'Layer dropdown picker to reference other comp layers', apply: {}, tags: ['reference', 'link', 'target'] },
  { id: 'point-control', label: 'Point Control', group: 'Expression Controls', hint: 'XY 2D coordinate point driver for tracking and expressions', apply: {}, tags: ['xy', 'coordinate', 'target'] },
  { id: 'slider-control', label: 'Slider Control', group: 'Expression Controls', hint: 'Floating point numerical slider to drive any parameter', apply: {}, tags: ['number', 'slider', 'master'] },

  // ── Generate ───────────────────────────────────────────────────────────────
  { id: '4-color-gradient', label: '4-Color Gradient', group: 'Generate', hint: 'Lush four-corner smooth color gradient wash', apply: { saturation: 120 }, tags: ['gradient', 'background', 'mesh'] },
  { id: 'advanced-lightning', label: 'Advanced Lightning', group: 'Generate', hint: 'Dynamic electric electrical arcs, sparks and plasma bolts', apply: { brightness: 20 }, tags: ['electricity', 'bolt', 'plasma'] },
  { id: 'audio-spectrum', label: 'Audio Spectrum', group: 'Generate', hint: 'Frequency band equalizer visualizer driven by audio track', apply: {}, tags: ['music', 'eq', 'bars', 'visualizer'] },
  { id: 'audio-waveform', label: 'Audio Waveform', group: 'Generate', hint: 'Oscilloscope audio sound wave visualizer line', apply: {}, tags: ['waveform', 'oscilloscope', 'sound'] },
  { id: 'beam', label: 'Beam', group: 'Generate', hint: 'Laser beam, tracer line, or sci-fi energy blast', apply: {}, tags: ['laser', 'tracer', 'light'] },
  { id: 'cc-glue-gun', label: 'Glue Gun', group: 'Generate', hint: 'Extrudes glossy 3D liquid gel trails along paths', apply: {}, tags: ['gel', 'glue', 'trail'] },
  { id: 'cc-light-burst-2-5', label: 'Light Burst 2.5', group: 'Generate', hint: 'Explosive radial light rays emanating from bright highlights', apply: { brightness: 25 }, tags: ['godrays', 'burst', 'shine'] },
  { id: 'cc-light-rays', label: 'Light Rays', group: 'Generate', hint: 'Volumetric light shafts and glowing spotlight center', apply: { brightness: 20 }, tags: ['shafts', 'volumetric', 'rays'] },
  { id: 'cc-light-sweep', label: 'Light Sweep', group: 'Generate', hint: 'Metallic sheen specular glint sweeping across layer', apply: { brightness: 15 }, tags: ['shine', 'glint', 'metallic', 'logo'] },
  { id: 'cc-threads', label: 'Threads', group: 'Generate', hint: 'Woven fabric, thread grids, and fiber textures', apply: {}, tags: ['fiber', 'weave', 'pattern'] },
  { id: 'cell-pattern', label: 'Cell Pattern', group: 'Generate', hint: 'Procedural cellular textures, crystals, and cobblestones', apply: {}, tags: ['cells', 'organic', 'voronoi'] },
  { id: 'checkerboard', label: 'Checkerboard', group: 'Generate', hint: 'Generates alternating colored checkerboard patterns', apply: {}, tags: ['tiles', 'pattern', 'checks'] },
  { id: 'circle', label: 'Circle', group: 'Generate', hint: 'Geometric circle or ring outline generator', apply: {}, tags: ['shape', 'ring', 'dot'] },
  { id: 'ellipse', label: 'Ellipse', group: 'Generate', hint: 'Geometric ellipse or oval shape generator', apply: {}, tags: ['shape', 'oval'] },
  { id: 'eyedropper-fill', label: 'Eyedropper Fill', group: 'Generate', hint: 'Samples a pixel coordinate and fills layer with color', apply: {}, tags: ['sample', 'fill', 'eyedropper'] },
  { id: 'fill', label: 'Fill', group: 'Generate', hint: 'Solid color overlay fill with adjustable opacity', apply: { brightness: 10 }, tags: ['solid', 'color', 'tint'] },
  { id: 'fractal', label: 'Fractal', group: 'Generate', hint: 'Mandelbrot and Julia set mathematical fractal patterns', apply: {}, tags: ['math', 'psychedelic', 'fractal'] },
  { id: 'gradient-ramp', label: 'Gradient Ramp', group: 'Generate', hint: 'Linear or radial two-color gradient transition', apply: {}, tags: ['ramp', 'sky', 'vignette'] },
  { id: 'grid', label: 'Grid', group: 'Generate', hint: 'Precision customizable grid overlay lines', apply: {}, tags: ['lines', 'rules', 'graph'] },
  { id: 'lens-flare', label: 'Lens Flare', group: 'Generate', hint: 'Optical camera lens flare with anamorphic rings and glints', apply: { brightness: 15 }, tags: ['anamorphic', 'sun', 'flare'] },
  { id: 'paint-bucket', label: 'Paint Bucket', group: 'Generate', hint: 'Flood-fills bounded color regions (magic fill bucket)', apply: {}, tags: ['flood', 'fill', 'bucket'] },
  { id: 'radio-waves', label: 'Radio Waves', group: 'Generate', hint: 'Propagating geometric radio pulses and radar ripples', apply: {}, tags: ['sonar', 'pulses', 'radar'] },
  { id: 'scribble', label: 'Scribble', group: 'Generate', hint: 'Fills masks with animated hand-drawn crayon scribbles', apply: {}, tags: ['sketch', 'doodle', 'crayon'] },
  { id: 'stroke', label: 'Stroke', group: 'Generate', hint: 'Outlines mask paths with animated brush strokes (write-on)', apply: {}, tags: ['outline', 'brush', 'path'] },
  { id: 'vegas', label: 'Vegas', group: 'Generate', hint: 'Neon marquee casino lights running along layer outlines', apply: { brightness: 25 }, tags: ['marquee', 'neon', 'lights'] },
  { id: 'write-on', label: 'Write-on', group: 'Generate', hint: 'Simulates handwriting text or signatures stroke by stroke', apply: {}, tags: ['signature', 'pen', 'draw'] },

  // ── Immersive Video / VR ───────────────────────────────────────────────────
  { id: 'vr-blur', label: 'VR Blur', group: 'Immersive Video / VR', hint: 'Seamless 360° spherical equirectangular blur without seam line', apply: { blur: 14 }, tags: ['360', 'equirectangular', 'vr'] },
  { id: 'vr-chromatic-aberrations', label: 'VR Chromatic Aberrations', group: 'Immersive Video / VR', hint: 'Optical lens fringe split calibrated for VR headsets', apply: { contrast: 10 }, tags: ['fringe', 'vr', 'optics'] },
  { id: 'vr-color-gradients', label: 'VR Color Gradients', group: 'Immersive Video / VR', hint: 'Seamless spherical horizon color gradients', apply: {}, tags: ['horizon', 'sky', 'vr'] },
  { id: 'vr-converter', label: 'VR Converter', group: 'Immersive Video / VR', hint: 'Converts between Equirectangular, Cubemap and Fisheye formats', apply: {}, tags: ['cubemap', 'convert', '360'] },
  { id: 'vr-de-noise', label: 'VR De-Noise', group: 'Immersive Video / VR', hint: 'Cleans up high-ISO noise on spherical 360 footage', apply: { blur: 4 }, tags: ['clean', 'denoise', 'vr'] },
  { id: 'vr-digital-glitch', label: 'VR Digital Glitch', group: 'Immersive Video / VR', hint: 'Procedural compression block tears and glitch artifacts for VR', apply: { contrast: 20 }, tags: ['glitch', 'artifacts', '360'] },
  { id: 'vr-fractal-noise', label: 'VR Fractal Noise', group: 'Immersive Video / VR', hint: 'Seamless equirectangular clouds, smoke, and atmospheric noise', apply: {}, tags: ['clouds', 'smoke', 'vr'] },
  { id: 'vr-glow', label: 'VR Glow', group: 'Immersive Video / VR', hint: 'Seamless bloom glow across 360 boundary meridians', apply: { brightness: 20, contrast: 15 }, tags: ['bloom', 'glow', 'vr'] },
  { id: 'vr-plane-to-sphere', label: 'VR Plane to Sphere', group: 'Immersive Video / VR', hint: 'Projects flat planar graphics into a 360° spherical panorama', apply: {}, tags: ['project', 'panorama', 'vr'] },
  { id: 'vr-rotate-sphere', label: 'VR Rotate Sphere', group: 'Immersive Video / VR', hint: 'Reorients pitch, roll, and yaw tilt in 360 video', apply: {}, tags: ['yaw', 'pitch', 'roll', '360'] },
  { id: 'vr-sharpen', label: 'VR Sharpen', group: 'Immersive Video / VR', hint: 'Sharpens spherical footage without pole pinch artifacts', apply: { contrast: 25 }, tags: ['crisp', 'vr', 'sharpen'] },
  { id: 'vr-sphere-to-plane', label: 'VR Sphere to Plane', group: 'Immersive Video / VR', hint: 'Pulls flat camera viewpoints out of 360 footage (Tiny Planet)', apply: {}, tags: ['tiny-planet', 'flat', 'extract'] },

  // ── Keying ─────────────────────────────────────────────────────────────────
  { id: 'advanced-spill-suppressor', label: 'Advanced Spill Suppressor', group: 'Keying', hint: 'Neutralizes green/blue bounce spill on hair and edges', apply: { saturation: 90 }, tags: ['green', 'blue', 'spill'] },
  { id: 'cc-simple-wire-removal', label: 'Simple Wire Removal', group: 'Keying', hint: 'Erases safety rigging wires and stunt cords seamlessly', apply: {}, tags: ['stunt', 'wire', 'clean'] },
  { id: 'color-difference-key', label: 'Color Difference Key', group: 'Keying', hint: 'Keys out complex backgrounds using difference equations', apply: {}, tags: ['chroma', 'difference', 'key'] },
  { id: 'color-range', label: 'Color Range', group: 'Keying', hint: 'Keys out a targeted range of colors in Lab or YUV space', apply: {}, tags: ['yuv', 'lab', 'isolate'] },
  { id: 'difference-matte', label: 'Difference Matte', group: 'Keying', hint: 'Subtracts an empty clean plate background to isolate moving subjects', apply: {}, tags: ['clean-plate', 'subtract', 'isolate'] },
  { id: 'extract', label: 'Extract', group: 'Keying', hint: 'High-speed luminance threshold keying for dark/light backdrops', apply: { contrast: 25 }, tags: ['luma', 'silhouette', 'threshold'] },
  { id: 'inner-outer-key', label: 'Inner/Outer Key', group: 'Keying', hint: 'Two-boundary matte isolation for hair and tricky edges', apply: {}, tags: ['hair', 'matte', 'edge'] },
  { id: 'key-cleaner', label: 'Key Cleaner', group: 'Keying', hint: 'Restores fine edge details and hair strands in keyed footage', apply: { contrast: 15 }, tags: ['hair', 'clean', 'edges'] },
  { id: 'keylight', label: 'Keylight (1.2)', group: 'Keying', hint: 'Industry-standard Academy Award winning green/blue screen keyer', apply: {}, tags: ['greenscreen', 'bluescreen', 'chroma'] },
  { id: 'linear-color-key', label: 'Linear Color Key', group: 'Keying', hint: 'Keys out a specific solid color with soft roll-off tolerance', apply: {}, tags: ['chroma', 'color', 'key'] },

  // ── Matte ──────────────────────────────────────────────────────────────────
  { id: 'matte-choker', label: 'Matte Choker', group: 'Matte', hint: 'Expands or contracts matte edges in two stages', apply: {}, tags: ['choke', 'erode', 'expand'] },
  { id: 'mocha-shape', label: 'Mocha Shape', group: 'Matte', hint: 'Imports multi-layer rotoscoping splines directly from Mocha', apply: {}, tags: ['mocha', 'roto', 'splines'] },
  { id: 'refine-hard-matte', label: 'Refine Hard Matte', group: 'Matte', hint: 'Cleans up motion edges for solid and mechanical objects', apply: {}, tags: ['hard', 'mechanical', 'edge'] },
  { id: 'refine-soft-matte', label: 'Refine Soft Matte', group: 'Matte', hint: 'Advanced edge calculation for fine wisps of hair, fur and smoke', apply: {}, tags: ['hair', 'fur', 'smoke', 'whisps'] },
  { id: 'simple-choker', label: 'Simple Choker', group: 'Matte', hint: 'Quick one-slider erosion or dilation of alpha matte edges', apply: {}, tags: ['erode', 'choke', 'trim'] },

  // ── Noise & Grain ──────────────────────────────────────────────────────────
  { id: 'add-grain', label: 'Add Grain', group: 'Noise & Grain', hint: 'Realistic film stock 35mm/16mm photochemical grain emulation', apply: { contrast: 5 }, tags: ['film', '35mm', 'organic', 'grain'] },
  { id: 'dust-scratches', label: 'Dust & Scratches', group: 'Noise & Grain', hint: 'Removes specks, dust, and scratches from vintage film scans', apply: { blur: 3 }, tags: ['clean', 'dust', 'vintage'] },
  { id: 'fractal-noise', label: 'Fractal Noise', group: 'Noise & Grain', hint: 'Essential procedural noise generator: Perlin, clouds, fire, water, textures', apply: {}, tags: ['perlin', 'smoke', 'clouds', 'fire'] },
  { id: 'match-grain', label: 'Match Grain', group: 'Noise & Grain', hint: 'Samples film grain from background plate and applies to VFX elements', apply: {}, tags: ['match', 'sample', 'plate'] },
  { id: 'median', label: 'Median', group: 'Noise & Grain', hint: 'Replaces pixels with median neighborhood values (removes pepper noise)', apply: { blur: 5 }, tags: ['median', 'smooth', 'clean'] },
  { id: 'median-legacy', label: 'Median (Legacy)', group: 'Noise & Grain', hint: 'Legacy implementation of median filter for project backward compatibility', apply: { blur: 5 }, tags: ['legacy', 'median'] },
  { id: 'noise', label: 'Noise', group: 'Noise & Grain', hint: 'Quick monochromatic or colored random pixel noise generator', apply: { contrast: 5 }, tags: ['grain', 'static', 'tv'] },
  { id: 'noise-alpha', label: 'Noise Alpha', group: 'Noise & Grain', hint: 'Adds random noise directly to the alpha transparency channel', apply: {}, tags: ['alpha', 'rough', 'dissolve'] },
  { id: 'noise-hls', label: 'Noise HLS', group: 'Noise & Grain', hint: 'Adds noise specifically to hue, lightness, or saturation channels', apply: {}, tags: ['hls', 'color', 'noise'] },
  { id: 'noise-hls-auto', label: 'Noise HLS Auto', group: 'Noise & Grain', hint: 'Animated cycling noise across HLS color channels', apply: {}, tags: ['animated', 'hls', 'noise'] },
  { id: 'remove-grain', label: 'Remove Grain', group: 'Noise & Grain', hint: 'High-end multi-channel temporal noise reduction and smoothing', apply: { blur: 4 }, tags: ['denoise', 'clean', 'smooth'] },
  { id: 'turbulent-noise', label: 'Turbulent Noise', group: 'Noise & Grain', hint: 'Fast GPU-optimized variant of fractal noise for motion graphics', apply: {}, tags: ['gpu', 'fast', 'smoke', 'mograph'] },

  // ── Perspective ────────────────────────────────────────────────────────────
  { id: '3d-camera-tracker', label: '3D Camera Tracker', group: 'Perspective', hint: 'Automatically tracks live-action 3D camera trajectory and points', apply: {}, tags: ['camera', 'solve', '3d', 'track'] },
  { id: '3d-glasses', label: '3D Glasses', group: 'Perspective', hint: 'Combines left/right stereo cameras into red/cyan anaglyph 3D', apply: { hue: 30 }, tags: ['anaglyph', 'stereo', '3d'] },
  { id: 'bevel-alpha', label: 'Bevel Alpha', group: 'Perspective', hint: 'Adds 3D beveled lighted chisel edges around alpha cutouts', apply: { brightness: 10, contrast: 15 }, tags: ['chisel', 'bevel', '3d', 'light'] },
  { id: 'bevel-edges', label: 'Bevel Edges', group: 'Perspective', hint: 'Applies a 3D beveled embossed picture frame border', apply: { contrast: 15 }, tags: ['frame', 'border', 'bevel'] },
  { id: 'cc-cylinder', label: 'Cylinder', group: 'Perspective', hint: 'Wraps 2D layer around a rotating 3D cylinder column', apply: {}, tags: ['can', 'cylinder', 'wrap', '3d'] },
  { id: 'cc-environment', label: 'Environment', group: 'Perspective', hint: 'Projects spherical reflection map onto 3D environment scenes', apply: {}, tags: ['hdri', 'reflection', 'map'] },
  { id: 'cc-sphere', label: 'Sphere', group: 'Perspective', hint: 'Wraps layer around a fully shaded, lit, and rotatable 3D sphere globe', apply: {}, tags: ['globe', 'planet', 'ball', '3d'] },
  { id: 'cc-spotlight', label: 'Spotlight', group: 'Perspective', hint: 'Casts an adjustable conical 3D spotlight cone across the layer', apply: { brightness: 20 }, tags: ['cone', 'light', 'spotlight'] },
  { id: 'drop-shadow', label: 'Drop Shadow', group: 'Perspective', hint: 'Adds realistic soft drop shadow behind layer with distance and blur', apply: {}, tags: ['shadow', 'depth', 'ui'] },
  { id: 'radial-shadow', label: 'Radial Shadow', group: 'Perspective', hint: 'Casts perspective shadows radiating from a point light source', apply: {}, tags: ['shadow', 'perspective', 'light'] },

  // ── Simulation / Particles ─────────────────────────────────────────────────
  { id: 'card-dance', label: 'Card Dance', group: 'Simulation / Particles', hint: 'Explodes layer into a 3D grid of flipping cards driven by gradients', apply: {}, tags: ['cards', 'grid', 'explode'] },
  { id: 'caustics', label: 'Caustics', group: 'Simulation / Particles', hint: 'Simulates underwater sunlight caustics and swimming pool reflections', apply: { brightness: 10, contrast: 15 }, tags: ['water', 'swimming', 'light'] },
  { id: 'cc-ball-action', label: 'Ball Action', group: 'Simulation / Particles', hint: 'Transforms picture into an array of bouncing 3D sphere voxels', apply: {}, tags: ['voxels', 'dots', 'matrix', 'explode'] },
  { id: 'cc-bubbles', label: 'Bubbles', group: 'Simulation / Particles', hint: 'Generates floating iridescent soap bubbles floating upward', apply: {}, tags: ['soap', 'bubbles', 'water'] },
  { id: 'cc-drizzle', label: 'Drizzle', group: 'Simulation / Particles', hint: 'Simulates raindrops hitting a water surface with concentric rings', apply: {}, tags: ['rain', 'puddle', 'rings'] },
  { id: 'cc-hair', label: 'Hair', group: 'Simulation / Particles', hint: 'Grows furry fiber strands and hair filaments from pixels', apply: {}, tags: ['fur', 'grass', 'strands'] },
  { id: 'cc-mr-mercury', label: 'Mr. Mercury', group: 'Simulation / Particles', hint: 'Blobby dripping liquid mercury drops that coalesce together', apply: { contrast: 20 }, tags: ['liquid', 'chrome', 'melt'] },
  { id: 'cc-particle-systems-ii', label: 'Particle Systems II', group: 'Simulation / Particles', hint: 'Classic high-speed 2D particle cannon: sparks, fire, fountains', apply: { brightness: 15 }, tags: ['cannon', 'sparks', 'fire'] },
  { id: 'cc-particle-world', label: 'Particle World', group: 'Simulation / Particles', hint: 'Full 3D particle generator with camera integration, physics, and gravity', apply: { brightness: 15 }, tags: ['3d', 'particles', 'sparks', 'snow', 'rain'] },
  { id: 'cc-pixel-polly', label: 'Pixel Polly', group: 'Simulation / Particles', hint: 'Shatters image into a shower of spinning polygon shards', apply: {}, tags: ['shatter', 'glass', 'explode'] },
  { id: 'cc-rainfall', label: 'Rainfall', group: 'Simulation / Particles', hint: 'Simulates realistic falling rain drops, wind drift, and puddles', apply: { brightness: -5, contrast: 10 }, tags: ['weather', 'rain', 'storm'] },
  { id: 'cc-scatterize', label: 'Scatterize', group: 'Simulation / Particles', hint: 'Disintegrates and dissolves pixels into floating dust clouds', apply: {}, tags: ['thanos', 'dust', 'dissolve'] },
  { id: 'cc-snowfall', label: 'Snowfall', group: 'Simulation / Particles', hint: 'Simulates gentle snowflakes drifting with turbulence and depth', apply: { brightness: 5 }, tags: ['winter', 'snow', 'flakes'] },
  { id: 'cc-star-burst', label: 'Star Burst', group: 'Simulation / Particles', hint: 'Hyperspace starfield flying toward or away from camera', apply: {}, tags: ['stars', 'warp', 'space', 'cosmos'] },
  { id: 'foam', label: 'Foam', group: 'Simulation / Particles', hint: 'Physics-based flowing bubbles, beer head, and foam clusters', apply: {}, tags: ['beer', 'lather', 'bubbles'] },
  { id: 'particle-playground', label: 'Particle Playground', group: 'Simulation / Particles', hint: 'Advanced particle physics engine with gravity wells and text particles', apply: {}, tags: ['physics', 'engine', 'gravity'] },
  { id: 'shatter', label: 'Shatter', group: 'Simulation / Particles', hint: 'Explosive brick walls, glass panes, puzzle pieces breaking apart', apply: {}, tags: ['explode', 'glass', 'brick', 'crack'] },
  { id: 'wave-world', label: 'Wave World', group: 'Simulation / Particles', hint: 'High-precision fluid wave simulation with reflectors and damping', apply: {}, tags: ['fluid', 'ripples', 'water'] },

  // ── Stylize ────────────────────────────────────────────────────────────────
  { id: 'brush-strokes', label: 'Brush Strokes', group: 'Stylize', hint: 'Simulates oil paint applied with coarse bristle brush strokes', apply: { contrast: 15 }, tags: ['paint', 'artistic', 'oil'] },
  { id: 'cartoon', label: 'Cartoon', group: 'Stylize', hint: 'Gives video cel-shaded flat comic book look with inked outlines', apply: { contrast: 35, saturation: 140 }, tags: ['comic', 'anime', 'cel-shaded'] },
  { id: 'cc-block-load', label: 'Block Load', group: 'Stylize', hint: 'Simulates dial-up internet chunky progressive bitmap loading', apply: {}, tags: ['retro', 'dialup', 'pixel'] },
  { id: 'cc-burn-film', label: 'Burn Film', group: 'Stylize', hint: 'Simulates movie projector film melting and burning in gate', apply: { brightness: 25, hue: 15 }, tags: ['burn', 'fire', 'film-burn'] },
  { id: 'cc-glass', label: 'Glass', group: 'Stylize', hint: 'Simulates embossed frosted or molded refractive glass surface', apply: { contrast: 20 }, tags: ['refract', 'frosted', '3d'] },
  { id: 'cc-hextile', label: 'HexTile', group: 'Stylize', hint: 'Repeats layer in a geometric hexagonal honeycomb pattern', apply: {}, tags: ['honeycomb', 'hexagon', 'pattern'] },
  { id: 'cc-kaleida', label: 'Kaleida', group: 'Stylize', hint: 'Hypnotic symmetrical kaleidoscope reflection mandalas', apply: {}, tags: ['mandala', 'mirror', 'symmetry'] },
  { id: 'cc-mr-smoothie', label: 'Mr. Smoothie', group: 'Stylize', hint: 'Smoothes and smears pixel flows into silky oil paint', apply: { blur: 6 }, tags: ['smooth', 'silk', 'smear'] },
  { id: 'cc-plastic', label: 'Plastic', group: 'Stylize', hint: 'Gives layer an embossed glossy shrink-wrapped plastic sheen', apply: { contrast: 25 }, tags: ['gloss', 'shrinkwrap', 'specular'] },
  { id: 'cc-repetile', label: 'RepeTile', group: 'Stylize', hint: 'Expands composition borders by tiling, flipping, or unfolding edges', apply: {}, tags: ['expand', 'infinite', 'tile'] },
  { id: 'cc-threshold', label: 'Threshold', group: 'Stylize', hint: 'Reduces image to stark black and white high-contrast graphics', apply: { contrast: 80 }, tags: ['bw', 'stark', 'graphic'] },
  { id: 'cc-threshold-rgb', label: 'Threshold RGB', group: 'Stylize', hint: 'Per-channel RGB thresholding for graphic print posterization', apply: { contrast: 70 }, tags: ['poster', 'print', 'pop-art'] },
  { id: 'cc-vignette', label: 'Vignette', group: 'Stylize', hint: 'Cinematic optical dark or light rounded border vignette', apply: { contrast: 10 }, tags: ['vignette', 'cinema', 'lens'] },
  { id: 'color-emboss', label: 'Color Emboss', group: 'Stylize', hint: 'Creates a raised relief stamp while preserving color information', apply: { contrast: 30 }, tags: ['stamp', 'relief', '3d'] },
  { id: 'emboss', label: 'Emboss', group: 'Stylize', hint: 'Converts layer into a gray stone or metal stamped relief', apply: { saturation: 0, contrast: 40 }, tags: ['stone', 'metal', 'relief'] },
  { id: 'find-edges', label: 'Find Edges', group: 'Stylize', hint: 'Identifies high-contrast edges and outlines in color or pencil lines', apply: { contrast: 50 }, tags: ['neon', 'sketch', 'lines'] },
  { id: 'glow', label: 'Glow', group: 'Stylize', hint: 'Lush neon light bloom radiating from highlights', apply: { brightness: 15, contrast: 20 }, tags: ['bloom', 'neon', 'radiance', 'laser'] },
  { id: 'mosaic', label: 'Mosaic', group: 'Stylize', hint: 'Pixelates picture into customizable rows and columns of mosaic tiles', apply: {}, tags: ['pixelate', '8bit', 'censor', 'tiles'] },
  { id: 'motion-tile', label: 'Motion Tile', group: 'Stylize', hint: 'Replicates layer across frame with mirror edges (essential for transitions)', apply: {}, tags: ['tile', 'mirror-edges', 'vfx'] },
  { id: 'posterize', label: 'Posterize', group: 'Stylize', hint: 'Quantizes color steps down to flat vintage print poster bands', apply: { contrast: 30 }, tags: ['retro', 'bands', 'vintage'] },
  { id: 'roughen-edges', label: 'Roughen Edges', group: 'Stylize', hint: 'Adds frayed, torn paper, or organic erosion to layer edges', apply: {}, tags: ['paper', 'torn', 'grunge'] },
  { id: 'scatter', label: 'Scatter', group: 'Stylize', hint: 'Randomly scatters pixels within neighborhood for frosted glass texture', apply: { blur: 4 }, tags: ['frosted', 'diffuse', 'rough'] },
  { id: 'strobe-light', label: 'Strobe Light', group: 'Stylize', hint: 'Flashes layer with rhythmic strobe pulses or transparency cuts', apply: { brightness: 30 }, tags: ['flash', 'rave', 'strobe'] },
  { id: 'texturize', label: 'Texturize', group: 'Stylize', hint: 'Embosses texture from another layer (canvas, brick, paper) onto source', apply: { contrast: 15 }, tags: ['canvas', 'paper', 'texture'] },
  { id: 'threshold', label: 'Threshold', group: 'Stylize', hint: 'Converts grayscale image into pure binary black and white pixels', apply: { contrast: 100 }, tags: ['binary', 'monochrome', 'stencil'] },

  // ── Text ───────────────────────────────────────────────────────────────────
  { id: 'numbers', label: 'Numbers', group: 'Text', hint: 'Generates animated counting numbers, dates, times, and decimals', apply: {}, tags: ['counter', 'score', 'digits'] },
  { id: 'timecode', label: 'Timecode', group: 'Text', hint: 'Displays burn-in SMPTE timecode (HH:MM:SS:FF) readout overlay', apply: {}, tags: ['burnin', 'smpte', 'counter'] },

  // ── Time ───────────────────────────────────────────────────────────────────
  { id: 'cc-force-motion-blur', label: 'Force Motion Blur', group: 'Time', hint: 'Synthesizes realistic optical motion blur across animated elements', apply: { blur: 6 }, tags: ['shutter', 'motion-blur', 'render'] },
  { id: 'cc-wide-time', label: 'Wide Time', group: 'Time', hint: 'Blends multiple preceding and succeeding frames into a light trail', apply: {}, tags: ['trails', 'ghost', 'echo'] },
  { id: 'echo', label: 'Echo', group: 'Time', hint: 'Repeats frame at past time intervals (motion trails / afterimages)', apply: {}, tags: ['trail', 'ghost', 'stutter'] },
  { id: 'pixel-motion-blur', label: 'Pixel Motion Blur', group: 'Time', hint: 'Calculates vector optical flow to add natural motion blur to video', apply: { blur: 8 }, tags: ['optical-flow', 'natural', 'blur'] },
  { id: 'posterize-time', label: 'Posterize Time', group: 'Time', hint: 'Locks video framerate to lower target (e.g. 12fps anime look or stop-motion)', apply: {}, tags: ['12fps', 'anime', 'stopmotion', 'stutter'] },
  { id: 'time-difference', label: 'Time Difference', group: 'Time', hint: 'Highlights only pixels that have changed between consecutive frames', apply: { contrast: 40 }, tags: ['motion-detection', 'delta'] },
  { id: 'time-displacement', label: 'Time Displacement', group: 'Time', hint: 'Shifts playback time across pixels based on a grayscale gradient map', apply: {}, tags: ['slitscan', 'timewarp', 'matrix'] },
  { id: 'timewarp', label: 'Timewarp', group: 'Time', hint: 'High-quality optical flow slow motion and speed ramps', apply: {}, tags: ['slow-mo', 'optical-flow', 'speed'] },

  // ── Transition ─────────────────────────────────────────────────────────────
  { id: 'block-dissolve', label: 'Block Dissolve', group: 'Transition', hint: 'Dissolves layer away in random pixelated square blocks', apply: {}, isTransition: true, tags: ['blocks', 'digital', 'wipe'] },
  { id: 'card-wipe', label: 'Card Wipe', group: 'Transition', hint: 'Flips layer over as rows and columns of turning 3D cards', apply: {}, isTransition: true, tags: ['cards', '3d', 'flip'] },
  { id: 'cc-glass-wipe', label: 'Glass Wipe', group: 'Transition', hint: 'Distorts image through refractive wavy glass as it transitions', apply: {}, isTransition: true, tags: ['glass', 'refraction', 'wipe'] },
  { id: 'cc-grid-wipe', label: 'Grid Wipe', group: 'Transition', hint: 'Transitions layer through expanding geometric grid holes', apply: {}, isTransition: true, tags: ['grid', 'matrix', 'wipe'] },
  { id: 'cc-image-wipe', label: 'Image Wipe', group: 'Transition', hint: 'Uses luminance values of another image as the wipe progression map', apply: {}, isTransition: true, tags: ['map', 'luma', 'wipe'] },
  { id: 'cc-jaws', label: 'Jaws', group: 'Transition', hint: 'Transitions between scenes with closing jagged teeth saw jaws', apply: {}, isTransition: true, tags: ['saw', 'teeth', 'jaws'] },
  { id: 'cc-light-wipe', label: 'Light Wipe', group: 'Transition', hint: 'Vaporizes layer with an intense glowing light beam sweep', apply: { brightness: 25 }, isTransition: true, tags: ['light', 'shine', 'beam'] },
  { id: 'cc-line-sweep', label: 'Line Sweep', group: 'Transition', hint: 'Sweeps layer away in scanning horizontal raster lines', apply: {}, isTransition: true, tags: ['scan', 'raster', 'lines'] },
  { id: 'cc-radial-scalewipe', label: 'Radial ScaleWipe', group: 'Transition', hint: 'Radial zoom stretch scaling wipe around a point', apply: {}, isTransition: true, tags: ['zoom', 'stretch', 'radial'] },
  { id: 'cc-scale-wipe', label: 'Scale Wipe', group: 'Transition', hint: 'Stretches and squashes layer into an edge until it vanishes', apply: {}, isTransition: true, tags: ['stretch', 'squash', 'wipe'] },
  { id: 'cc-twister', label: 'Twister', group: 'Transition', hint: 'Twists layer around a central 3D vortex funnel into the next cut', apply: {}, isTransition: true, tags: ['tornado', 'twirl', 'funnel'] },
  { id: 'cc-warpomatic', label: 'WarpoMatic', group: 'Transition', hint: 'Bizarre warp morph transition between two scenes', apply: {}, isTransition: true, tags: ['morph', 'warp', 'cut'] },
  { id: 'gradient-wipe', label: 'Gradient Wipe', group: 'Transition', hint: 'Wipes across scene following a grayscale gradient mask map', apply: {}, isTransition: true, tags: ['soft', 'burn', 'cloud-wipe'] },
  { id: 'iris-wipe', label: 'Iris Wipe', group: 'Transition', hint: 'Classic circular or diamond expanding camera shutter aperture wipe', apply: {}, isTransition: true, tags: ['circle', 'iris', 'looney-tunes'] },
  { id: 'linear-wipe', label: 'Linear Wipe', group: 'Transition', hint: 'Clean angled linear sweep with adjustable feather soft edge', apply: {}, isTransition: true, tags: ['sweep', 'angled', 'feather'] },
  { id: 'radial-wipe', label: 'Radial Wipe', group: 'Transition', hint: 'Clock hand 360° sweeping transition around center anchor', apply: {}, isTransition: true, tags: ['clock', 'radar', 'sweep'] },
  { id: 'venetian-blinds', label: 'Venetian Blinds', group: 'Transition', hint: 'Reveals layer through rotating horizontal or vertical window slats', apply: {}, isTransition: true, tags: ['slats', 'blinds', 'lines'] },

  // ── Utility ────────────────────────────────────────────────────────────────
  { id: 'apply-color-lut', label: 'Apply Color LUT', group: 'Utility', hint: 'Applies standard .cube or .3dl 3D Look-Up Table cinema film grades', apply: { contrast: 15, saturation: 110 }, tags: ['lut', 'cube', 'cinema', 'grade'] },
  { id: 'cc-overbrights', label: 'Overbrights', group: 'Utility', hint: 'Visualizes and highlights pixels exceeding 100% white IRE luminance', apply: {}, tags: ['zebra', 'clipping', 'inspect'] },
  { id: 'cineon-converter', label: 'Cineon Converter', group: 'Utility', hint: 'Converts Kodak Cineon film log scans to linear color space', apply: { contrast: 20 }, tags: ['log', 'film', 'cineon'] },
  { id: 'color-profile-converter', label: 'Color Profile Converter', group: 'Utility', hint: 'Converts between sRGB, Rec.709, Rec.2020, Display P3, and ACES', apply: {}, tags: ['aces', 'rec709', 'p3', 'color-space'] },
  { id: 'grow-bounds', label: 'Grow Bounds', group: 'Utility', hint: 'Expands layer raster buffer to prevent effects from clipping at edges', apply: {}, tags: ['buffer', 'bounds', 'expand'] },
  { id: 'hdr-compander', label: 'HDR Compander', group: 'Utility', hint: 'Compresses or expands High Dynamic Range float pixel depth', apply: { contrast: 10 }, tags: ['hdr', 'compress', 'expand'] },
  { id: 'hdr-highlight-compression', label: 'HDR Highlight Compression', group: 'Utility', hint: 'Tames specular highlights in 32-bit HDR floating point comps', apply: { brightness: -5, contrast: 10 }, tags: ['highlights', 'soft-knee', 'hdr'] },

  // ── Obsolete / Legacy ──────────────────────────────────────────────────────
  { id: 'basic-3d', label: 'Basic 3D', group: 'Obsolete / Legacy', hint: 'Legacy lightweight swivel and tilt 3D transformation with specular glint', apply: {}, tags: ['tilt', 'swivel', 'legacy'] },
  { id: 'basic-text', label: 'Basic Text', group: 'Obsolete / Legacy', hint: 'Legacy fixed raster text generator', apply: {}, tags: ['text', 'legacy'] },
  { id: 'color-key', label: 'Color Key', group: 'Obsolete / Legacy', hint: 'Legacy simple color range keyer', apply: {}, tags: ['key', 'legacy'] },
  { id: 'gaussian-blur-legacy', label: 'Gaussian Blur (Legacy)', group: 'Obsolete / Legacy', hint: 'Non-GPU legacy Gaussian blur algorithm from older After Effects versions', apply: { blur: 12 }, tags: ['blur', 'legacy'] },
  { id: 'lightning', label: 'Lightning', group: 'Obsolete / Legacy', hint: 'Classic two-point electric lightning arc generator', apply: { brightness: 20 }, tags: ['electric', 'legacy'] },
  { id: 'luma-key', label: 'Luma Key', group: 'Obsolete / Legacy', hint: 'Legacy keying filter based on brightness thresholds', apply: { contrast: 30 }, tags: ['luma', 'legacy'] },
  { id: 'path-text', label: 'Path Text', group: 'Obsolete / Legacy', hint: 'Legacy text warping along bezier vector paths', apply: {}, tags: ['path', 'text', 'legacy'] },
  { id: 'reduce-interlace-flicker', label: 'Reduce Interlace Flicker', group: 'Obsolete / Legacy', hint: 'Blurs alternating scanlines to combat CRT interlace buzz', apply: { blur: 1 }, tags: ['crt', 'interlace', 'flicker'] },
  { id: 'spill-suppressor', label: 'Spill Suppressor', group: 'Obsolete / Legacy', hint: 'Original legacy green/blue spill color suppressor', apply: { saturation: 95 }, tags: ['spill', 'legacy'] },
];

/** Incomplete legacy entries stay readable in saved projects, but cannot be applied as working effects. */
export const AVAILABLE_EFFECTS = ALL_EFFECTS.filter(effect => RENDERED_EFFECTS.has(effect.id));

/** Quick dictionary of all effects by ID */
export const EFFECT_MAP = new Map<string, EffectDefinition>(ALL_EFFECTS.map((eff) => [eff.id, eff]));

/** Category counts helper */
export const CATEGORY_COUNTS = EFFECT_CATEGORIES.reduce((acc, cat) => {
  acc[cat] = ALL_EFFECTS.filter((eff) => eff.group === cat).length;
  return acc;
}, {} as Record<EffectCategory, number>);
