// Premiere Pro's default Windows keyboard layout, as Helios implements it. Shown in the
// Keyboard Shortcuts dialog; the handler lives in App.tsx.
export const SHORTCUTS: [string, string, string][] = [
  ['Ctrl+Alt+N', 'New project', 'File'],
  ['Ctrl+N', 'New comp', 'File'],
  ['Ctrl+O', 'Open project', 'File'],
  ['Ctrl+S', 'Save', 'File'],
  ['Ctrl+Shift+S', 'Save as', 'File'],
  ['Ctrl+Alt+S', 'Save a copy', 'File'],
  ['Ctrl+I', 'Import media', 'File'],
  ['Ctrl+M', 'Export media', 'File'],
  ['Ctrl+Shift+E', 'Export frame', 'File'],
  ['Ctrl+/', 'New folder', 'File'],
  ['Ctrl+Q', 'Quit', 'File'],

  ['Ctrl+Z', 'Undo', 'Edit'],
  ['Ctrl+Shift+Z · Ctrl+Y', 'Redo', 'Edit'],
  ['Ctrl+X', 'Cut', 'Edit'],
  ['Ctrl+C', 'Copy', 'Edit'],
  ['Ctrl+V', 'Paste at the playhead', 'Edit'],
  ['Ctrl+Shift+V', 'Paste insert', 'Edit'],
  ['Ctrl+Alt+V', 'Paste attributes', 'Edit'],
  ['Delete', 'Clear', 'Edit'],
  ['Shift+Delete', 'Ripple delete', 'Edit'],
  ['Ctrl+Shift+/', 'Duplicate', 'Edit'],
  ['Ctrl+A', 'Select all', 'Edit'],
  ['Ctrl+Shift+A', 'Deselect all', 'Edit'],
  ['Ctrl+F', 'Find in the Project panel', 'Edit'],
  ['Ctrl+E', 'Edit original', 'Edit'],
  ['Ctrl+Alt+K', 'Keyboard shortcuts', 'Edit'],
  ['Ctrl+,', 'Settings', 'Edit'],

  ['V', 'Selection tool', 'Tools'],
  ['A · Shift+A', 'Track select forward · backward', 'Tools'],
  ['B', 'Ripple edit tool', 'Tools'],
  ['N', 'Rolling edit tool', 'Tools'],
  ['R', 'Rate stretch tool', 'Tools'],
  ['C', 'Razor tool', 'Tools'],
  ['Y', 'Slip tool', 'Tools'],
  ['U', 'Slide tool', 'Tools'],
  ['P', 'Pen tool (keyframes and pen masks)', 'Tools'],
  ['H', 'Hand tool', 'Tools'],
  ['Z', 'Zoom tool', 'Tools'],
  ['T', 'Type tool', 'Tools'],
  ['Ctrl+Alt+R · Ctrl+Alt+E', 'Rectangle · Ellipse tool', 'Tools'],

  ['Space', 'Play / stop the focused monitor', 'Playback'],
  ['J · K · L', 'Shuttle back · stop · forward (press again for 2×, 4×, 8×)', 'Playback'],
  ['Shift+K', 'Play around the playhead', 'Playback'],
  ['← →', 'Step one frame (Shift: five)', 'Playback'],
  ['↑ ↓', 'Previous · next edit point on targeted tracks (Shift: any track)', 'Playback'],
  ['Home · End', 'Comp start · end', 'Playback'],
  ['Page Up · Page Down', 'Jump five seconds', 'Playback'],

  ['I · O', 'Mark In · Out', 'Marking'],
  ['X', 'Mark clip', 'Marking'],
  ['/', 'Mark selection', 'Marking'],
  ['Shift+I · Shift+O', 'Go to In · Out', 'Marking'],
  ['Ctrl+Shift+I · Ctrl+Shift+O', 'Clear In · Out', 'Marking'],
  ['Ctrl+Shift+X', 'Clear In and Out', 'Marking'],
  ['M', 'Add or remove marker', 'Marking'],
  ['Shift+M · Ctrl+Shift+M', 'Next · previous marker', 'Marking'],
  ['Ctrl+Alt+M', 'Clear the marker at the playhead', 'Marking'],
  ['Ctrl+Alt+Shift+M', 'Clear all markers', 'Marking'],

  [', · .', 'Insert · overwrite from the Source monitor', 'Editing'],
  ['Ctrl+K', 'Add edit on targeted tracks', 'Editing'],
  ['Ctrl+Shift+K', 'Add edit on every track', 'Editing'],
  ['Q · W', 'Ripple trim previous · next edit to the playhead', 'Editing'],
  ['Shift+Q · Shift+W', 'Extend previous · next edit to the playhead', 'Editing'],
  ['; · \'', 'Lift · extract the In to Out range', 'Editing'],
  ['Ctrl+D · Ctrl+Shift+D', 'Apply default video · audio transition', 'Editing'],
  ['Ctrl+R', 'Speed / Duration', 'Editing'],
  ['Shift+E', 'Enable or disable clips', 'Editing'],
  ['Ctrl+L', 'Link or unlink audio and video', 'Editing'],
  ['Ctrl+G · Ctrl+Shift+G', 'Group · ungroup', 'Editing'],
  ['Shift+G', 'Audio gain', 'Editing'],
  ['F', 'Match frame', 'Editing'],
  ['Alt + drag a clip edge', 'Stretch or squish the clip (rate stretch)', 'Editing'],
  ['Ctrl + drag a clip edge', 'Ripple trim', 'Editing'],
  ['Ctrl+Shift + drag a clip edge', 'Rolling edit', 'Editing'],
  ['Alt + drag a clip', 'Duplicate it', 'Editing'],
  ['Ctrl + drop a clip', 'Insert instead of overwrite', 'Editing'],
  ['Alt + click a clip', 'Select it without its linked partner', 'Editing'],
  ['Ctrl + click a rubber band', 'Add a keyframe', 'Editing'],
  ['Alt + ← →', 'Nudge the selection one frame (Shift: five)', 'Editing'],
  ['Alt + ↑ ↓', 'Nudge the selection one track', 'Editing'],
  ['[ · ]', 'Clip volume down · up 1 dB (Shift: 6 dB)', 'Editing'],

  ['S', 'Snap in timeline', 'Timeline'],
  ['= · -', 'Zoom in · out', 'Timeline'],
  ['\\', 'Zoom to the whole comp (again to go back)', 'Timeline'],
  ['Shift+= · Shift+_', 'Expand · minimize all tracks', 'Timeline'],
  ['Ctrl+= · Ctrl+-', 'Taller · shorter video tracks', 'Timeline'],
  ['Alt+= · Alt+-', 'Taller · shorter audio tracks', 'Timeline'],
  ['Alt + wheel', 'Zoom around the pointer', 'Timeline'],
  ['Shift + wheel', 'Scroll sideways', 'Timeline'],

  ['Shift+1…Shift+7', 'Project · Source · Timeline · Program · Properties · Meters · Tools', 'Panels'],
  ['Ctrl+Alt+L', 'Show or hide Helios AI', 'Panels'],
  ['`', 'Maximize the panel under the cursor (or focused panel)', 'Panels'],
  ['Escape', 'Deselect and go back to the Selection tool', 'Panels'],
];
