// What the chat calls each tool while it runs.
//
// A tool call shows up in the chat as a row, and that row used to be the tool's snake_case name
// title-cased ("Run frame qa", "Place sfx", "Get comp"), which reads like code. These labels say
// what is happening from the editor's side of the screen, in the words an editor would use:
// present participle, sentence case, 30 characters at most, no trailing punctuation. Every tool
// in ai-tools.json has one (tests/toolLabels.test.ts holds that); a tool added later without one
// falls back to its name with spaces, the way the row read before.

export const TOOL_LABELS: Record<string, string> = {
  editing_workflow_status: 'Checking the plan',
  verify_edit_workflow: 'Verifying the edit',
  tool_help: 'Checking how a step works',
  propose_storyboards: 'Drafting storyboard ideas',
  judge_edit: 'Reviewing the cut',
  install_local_model: 'Downloading an AI model',
  online_research: 'Researching online',
  scrape_web_page: 'Reading a web page',
  scrape_videos: 'Finding videos on a page',
  query_frame_atlas: 'Looking up shot references',
  synthesize_speech_voiceover: 'Recording a voice-over',
  download_online_media: 'Downloading media',
  create_project_guideline: 'Writing a style guide',
  add_text_behind_subject: 'Adding text behind the subject',
  score_audio_clip: 'Shaping audio levels',
  inspect_clip_frames: 'Watching frames',
  inspect_source_frames: 'Watching source frames',
  save_storyboard: 'Saving the storyboard',
  save_video_blueprint: 'Saving the video plan',
  execute_blueprint: 'Following the video plan',
  depth_occlusion_clip: 'Mapping depth in a clip',
  add_media_behind_subject: 'Placing media behind subject',
  local_media_capabilities: 'Checking local generators',
  generate_local_media: 'Generating media locally',
  cloud_generation_capabilities: 'Checking cloud generators',
  generate_cloud_media: 'Generating clips in the cloud',
  generation_job: 'Checking a generation',
  import_generated_media: 'Importing generated media',
  rotoscope_clip: 'Rotoscoping a clip',
  analyze_clip_speech: 'Listening to the speech',
  podcast_cut: 'Cutting the podcast',
  track_people: 'Tracking people',
  get_project: 'Reading the project',
  get_comp: 'Reading the timeline',
  apply_edit: 'Editing the timeline',
  list_recipes: 'Browsing edit recipes',
  apply_recipe: 'Applying an edit recipe',
  ask_user: 'Asking you',
  create_comp: 'Creating a new comp',
  update_comp: 'Changing comp settings',
  open_comp: 'Opening a comp',
  choose_shorts_format: 'Asking for the shorts format',
  choose_comp_size: 'Asking for the frame size',
  create_shorts: 'Making shorts',
  create_item: 'Adding a project item',
  update_item: 'Changing a project item',
  create_folder: 'Creating a folder',
  delete_project_items: 'Removing project items',
  import_media: 'Importing media',
  add_tracks: 'Adding tracks',
  update_track: 'Changing a track',
  delete_tracks: 'Deleting tracks',
  place_clip: 'Placing a clip',
  add_text: 'Adding text',
  add_captions: 'Adding captions',
  add_sound_effect: 'Adding a sound effect',
  add_voiceover: 'Adding a voice-over',
  update_clip: 'Adjusting a clip',
  delete_clips: 'Deleting clips',
  split_clips: 'Splitting clips',
  remove_range: 'Cutting a range',
  nest_clips: 'Making a comp',
  link_clips: 'Linking clips',
  list_caption_styles: 'Browsing caption styles',
  set_caption_style: 'Setting the caption style',
  add_marker: 'Adding a marker',
  set_in_out: 'Setting in and out points',
  set_playhead: 'Moving the playhead',
  undo: 'Undoing',
  add_transition: 'Adding a transition',
  remove_transitions: 'Removing transitions',
  set_keyframes: 'Setting keyframes',
  set_mask: 'Masking a clip',
  add_shape: 'Drawing a shape',
  add_plugin_clip: 'Adding a plugin clip',
  frame_hold: 'Holding a frame',
  group_clips: 'Grouping clips',
  detect_scenes: 'Finding scene cuts',
  normalize_audio: 'Normalizing audio',
  list_effects: 'Browsing effects',
  edit_effect: 'Adjusting an effect',
  inspect_color: 'Checking the color',
  color_grade: 'Grading color',
  list_learned_skills: 'Looking up learned edits',
  apply_learned_skill: 'Applying a learned edit',
  generate_selection_sound: 'Adding sound accents',
  create_stick_figure: 'Drawing a stick figure',
  create_custom_tool: 'Building a custom tool',
  list_custom_tools: 'Checking custom tools',
  call_custom_tool: 'Running a custom tool',
  update_custom_tool: 'Improving a custom tool',
  delete_custom_tool: 'Deleting a custom tool',
  brain_remember: 'Remembering this',
  brain_recall: 'Recalling past work',
  brain_forget: 'Forgetting a memory',
  brain_save_skill: 'Saving a how-to',
  brain_load_skill: 'Loading a how-to',
  read_file: 'Reading a file',
  write_file: 'Writing a file',
  edit_file: 'Editing a file',
  list_directory: 'Listing a folder',
  glob_search: 'Finding files',
  grep_search: 'Searching files',
  run_command: 'Running a command',
  add_graphic: 'Adding a graphic',
  create_motion_graphic: 'Creating a motion graphic',
  react_bits: 'Browsing animated UI pieces',
  remotion_kit: 'Browsing motion presets',
  list_brand_kits: 'Checking brand kits',
  get_brand_kit: 'Reading the brand kit',
  list_brand_archetypes: 'Browsing brand styles',
  create_brand_kit: 'Creating a brand kit',
  update_brand_kit: 'Updating the brand kit',
  delete_brand_kit: 'Deleting a brand kit',
  set_active_brand_kit: 'Choosing a brand kit',
  apply_brand_kit: 'Applying the brand kit',
  brand_kit_prompt: 'Getting brand image rules',
  render_brand_board: 'Showing the brand board',
  import_brand_logo: 'Importing the brand logo',
  export_brand_kit: 'Exporting the brand kit',
  import_brand_kit: 'Importing a brand kit',
  consult_council: 'Asking the review council',
  find_free_media: 'Finding free media',
  spawn_subagent: 'Starting a helper agent',
  wait_subagent: 'Waiting for a helper agent',
  list_subagents: 'Checking helper agents',
  attach_production_asset: 'Matching media to a shot',
  finish_gathering: 'Wrapping up gathering',
  compose_music: 'Composing music',
  make_background: 'Making a background',
  build_edit_from_brief: 'Building the whole edit',
  run_frame_qa: 'Checking frames',
  organize_bin: 'Organizing the project bin',
  fill_background: 'Filling the background',
  layout_clip: 'Reframing a clip',
  split_screen: 'Making a split screen',
  seamless_transition: 'Adding a seamless cut',
  analyze_music_beats: 'Finding the music beats',
  analyze_song: 'Mapping the song',
  snap_cuts_to_beats: 'Snapping cuts to the beat',
  level_audio: 'Leveling the audio',
  erase_subject_clip: 'Erasing the subject',
  reveal_subject: 'Revealing the subject',
  list_motion_templates: 'Browsing motion templates',
  list_character_actions: 'Browsing character actions',
  list_characters: 'Browsing characters',
  create_character: 'Adding a character',
  animate_character: 'Animating a character',
  lip_sync_character: 'Lip-syncing a character',
  check_pacing: 'Checking the pacing',
  import_lottie: 'Importing a Lottie animation',
  add_fx: 'Adding a motion accent',
  list_transitions: 'Browsing transitions',
  create_motion_sequence: 'Building a motion sequence',
  capture_product_ui: 'Screenshotting your product',
  list_ui_kinds: 'Browsing UI screens',
  create_ui_screen: 'Building a UI screen',
  update_ui_screen: 'Updating a UI screen',
  list_3d_presets: 'Browsing 3D presets',
  render_3d_scene: 'Rendering a 3D scene',
  motion_guide: 'Reading the motion guide',
  list_drawn_styles: 'Browsing hand-drawn styles',
  check_motion_arcs: 'Checking motion arcs',
  search_icons: 'Searching icons',
  svg_to_shape: 'Turning an SVG into a shape',
  create_motion_scene: 'Creating a motion scene',
  get_motion_scene: 'Reading a motion scene',
  update_motion_scene: 'Updating a motion scene',
  analyze_reference_video: 'Studying a reference video',
  save_style_profile: 'Saving the style profile',
  track_motion: 'Tracking motion',
  nest_motion_scenes: 'Putting motion scenes in comps',
  split_motion_layers: 'Splitting motion layers',
  get_brand_guideline: 'Reading brand guidelines',
  extract_brand_from_url: 'Reading a brand from a site',
  check_brand_compliance: 'Checking brand consistency',
  train_brand_kit: 'Teaching the brand kit',
  forget_training: 'Undoing brand training',
  search_memes: 'Searching memes',
  find_memes_online: 'Finding memes online',
  refresh_meme_trends: 'Checking meme trends',
  save_meme: 'Saving a meme',
  get_meme_media: 'Downloading a meme',
  find_receipt: 'Finding the exact quote',
  search_sfx: 'Searching sound effects',
  place_sfx: 'Adding a sound effect',
  cutout_image: 'Cutting out a subject',
  detect_faces: 'Finding faces',
  key_green_screen: 'Keying the green screen',
  save_beat_sheet: 'Saving the beat sheet',
  roast_move: 'Making a comedy edit',
  validate_roast_edl: 'Checking the roast plan',
  apply_roast_edl: 'Assembling the roast edit',
  edit_dna: 'Measuring the edit rhythm',
  plugin_sdk_reference: 'Reading plugin docs',
  list_plugins: 'Checking plugins',
  get_plugin: 'Reading a plugin',
  save_plugin: 'Saving a plugin',
  plugin_scaffold: 'Starting a new plugin',
  plugin_list_files: 'Listing plugin files',
  plugin_read_file: 'Reading a plugin file',
  plugin_write_file: 'Writing a plugin file',
  plugin_add_library: 'Adding a library to a plugin',
  plugin_add_asset: 'Adding media to a plugin',
  plugin_delete_file: 'Deleting a plugin file',
  plugin_validate: 'Checking a plugin',
  plugin_test: 'Testing a plugin',
  plugin_screenshot: 'Previewing a plugin',
  plugin_save: 'Installing a plugin',
  plugin_examples: 'Browsing plugin examples',
  plugin_tool_catalog: 'Checking what plugins can do',
  plugin_logs: 'Reading plugin logs',
  call_plugin_action: 'Running a plugin action',
  show_plugin: 'Showing a plugin',
  delete_plugin: 'Deleting a plugin',
};

/** The chat row's label for a tool: its plain-English label, or its name with spaces. */
export function toolLabel(name: string): string {
  const label = TOOL_LABELS[name];
  if (label) return label;
  const spaced = name.replace(/_/g, ' ');
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}
