import {describe,it,expect} from 'vitest';
import {ALL_EFFECTS,AVAILABLE_EFFECTS,EFFECT_MAP} from '../src/lib/effectsCatalog';
import {getEffectSchema,createAppliedEffect,computeAppliedEffects} from '../src/lib/effectFilters';
import {RENDERED_EFFECTS} from '../src/lib/effectExport';
import {normalizeEffectClip} from '../src/lib/effectState';
import {newClip} from '../src/lib/timeline';
import {bakeGrade} from '../src/lib/colorGrade';
describe('native effect contracts',()=>{
it('excludes Cinema 4D and uses Bhippi branding',()=>{expect(ALL_EFFECTS.some(e=>e.id==='cineware')).toBe(false);expect(EFFECT_MAP.get('lumetri-color')?.label).toBe('Bhippi Color Studio');expect(AVAILABLE_EFFECTS.some(e=>/^(CC |Mocha|Lumetri)/.test(e.label))).toBe(false);});
it('only offers effects with preview and export support',()=>{expect(AVAILABLE_EFFECTS.length).toBe(15);for(const effect of AVAILABLE_EFFECTS){expect(RENDERED_EFFECTS.has(effect.id)).toBe(true);expect(getEffectSchema(effect.id)).toBeDefined();}});
it('does not bake a new stack effect into base adjustments',()=>{const fx=createAppliedEffect(EFFECT_MAP.get('brightness-contrast')!);const clip=newClip({trackId:'v',source:{type:'shape',shape:'rectangle',sides:4,fill:'#ffffff',stroke:null,strokeWidth:0,width:100,height:100,cornerRadius:0},duration:5,start:0});clip.appliedEffects=[fx];const normalized=normalizeEffectClip(clip);expect(normalized.effects).toEqual(clip.effects);expect(fx.stackOnly).toBe(true);expect(computeAppliedEffects('x',[]).cssFilters).toEqual([]);});
it('migrates only duplicated legacy values and preserves manual changes',()=>{const definition=EFFECT_MAP.get('lumetri-color')!;const clip=newClip({trackId:'v',source:{type:'media',assetId:'a'},duration:5,start:0});clip.effects={...clip.effects,...definition.apply,brightness:37};clip.appliedEffects=[{...createAppliedEffect(definition),stackOnly:undefined}];const migrated=normalizeEffectClip(clip);expect(migrated.effects.contrast).toBe(0);expect(migrated.effects.saturation).toBe(100);expect(migrated.effects.brightness).toBe(37);expect(normalizeEffectClip(migrated)).toEqual(migrated);});
it('all grading tonal controls change the baked grade',()=>{const fx=createAppliedEffect(EFFECT_MAP.get('lumetri-color')!);const base=Array.from(bakeGrade(fx.params).data);for(const key of ['highlights','shadows','whites','blacks','temperature','tint','shadowAmount','midtoneAmount','highlightAmount','liftY','gammaB','gainR','offsetG','vibrance','sliceSkinSat'])expect(Array.from(bakeGrade({...fx.params,[key]:key.startsWith('lift')||key.startsWith('gamma')||key.startsWith('gain')||key.startsWith('offset')?0.2:40}).data),key).not.toEqual(base);});
it('four-color gradient creates an actual compositing filter',()=>{const fx=createAppliedEffect(EFFECT_MAP.get('4-color-gradient')!);expect(getEffectSchema(fx.effectId).params.filter(p=>p.type==='color')).toHaveLength(4);expect(computeAppliedEffects('c',[fx]).svgDefs).toHaveLength(1);});
it('keylight and extract create hardware-accelerated SVG keying filters',()=>{const keylight=createAppliedEffect(EFFECT_MAP.get('keylight')!);const extract=createAppliedEffect(EFFECT_MAP.get('extract')!);expect(getEffectSchema(keylight.effectId).params.some(p=>p.id==='screenColor')).toBe(true);expect(computeAppliedEffects('clip-1',[keylight]).svgDefs).toHaveLength(1);expect(computeAppliedEffects('clip-2',[extract]).svgDefs).toHaveLength(1);});
});
