// The live-model eval: real small models (free, through opencode) get twelve editing requests and
// the create_motion_graphic tool as the app describes it; what they call is built and scored like
// the fixed eval (src/lib/templateEval.ts). A refused call gets its error back for one retry, as in
// the agent loop. The calls are saved, so later changes re-score them without calling a model:
//
//   LIVE_MODELS=opencode/big-pickle,opencode/muse-spark-1.3-contributor-free npx vitest run tests/liveModelEval.test.ts
//     calls the models, saves docs/benchmarks/live-calls/<model>.json, writes docs/benchmarks/live-models.md
//   npx vitest run tests/liveModelEval.test.ts
//     replays the saved calls through the current tools (free, deterministic)
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import tools from '../src/lib/ai-tools.json';
import { BRIEFS, jsonFromReply, liveCase, livePrompt, norm, scoreCase, type Brief } from '../src/lib/templateEval';
import { runCase } from './evalHost';

const CALLS_DIR = 'docs/benchmarks/live-calls';
type Attempt = { args: Record<string, unknown> | null; reply?: string; error?: string };
type Call = { brief: string; attempts: Attempt[] };
type Row = { brief: Brief; verdict: 'good' | 'recovered' | 'bad'; templateOk: boolean; factsShown: boolean; template: string; problems: string[] };

const toolSpec = (tools as unknown as { tools: { name: string }[] }).tools.find((tool) => tool.name === 'create_motion_graphic');
const fileOf = (model: string) => join(CALLS_DIR, `${model.replace(/[^a-z0-9.-]+/gi, '_')}.json`);

function ask(model: string, prompt: string): Promise<string> {
  const cwd = join(tmpdir(), 'bhippi-live-eval');
  mkdirSync(cwd, { recursive: true });
  return new Promise((resolve) => {
    const child = spawn('opencode', ['run', '-m', model], { cwd, shell: true });
    let out = '';
    const timer = setTimeout(() => { child.kill(); resolve(out); }, 180_000);
    child.stdout.on('data', (chunk) => { out += chunk; });
    child.stderr.on('data', (chunk) => { out += chunk; });
    child.on('close', () => { clearTimeout(timer); resolve(out); });
    child.stdin.end(prompt);
  });
}

/** Builds each attempt in order until one works; returns the row for the brief. */
async function score(brief: Brief, attempts: Attempt[], model: string): Promise<Row> {
  let last: Row | null = null;
  for (const [i, attempt] of attempts.entries()) {
    if (!attempt.args) { last = { brief, verdict: 'bad', templateOk: false, factsShown: false, template: '', problems: ['no JSON in the reply'] }; continue; }
    const c = liveCase(brief, attempt.args, model);
    const outcome = await runCase(c);
    const scored = scoreCase(c, outcome);
    const shown = norm(outcome.texts.join(' '));
    const row: Row = {
      brief,
      verdict: outcome.ok && scored.verdict === 'good' ? (i === 0 ? 'good' : 'recovered') : 'bad',
      templateOk: brief.templates.includes(c.template),
      factsShown: outcome.ok && (brief.words ?? []).every((w) => shown.includes(norm(w))) && (brief.numbers ?? []).every((n) => shown.includes(String(n))),
      template: c.template,
      problems: outcome.ok ? scored.problems : [`refused: ${(outcome.error ?? '').slice(0, 140)}`],
    };
    last = row;
    if (row.verdict !== 'bad') return row;
  }
  return last!;
}

function markdown(results: Record<string, Row[]>): string {
  const pct = (n: number, d: number) => `${Math.round((n / Math.max(1, d)) * 100)}%`;
  const lines = [
    '# Live small-model eval',
    '',
    'Generated by `tests/liveModelEval.test.ts`: each model gets the twelve requests in `BRIEFS` (`src/lib/templateEval.ts`) and the `create_motion_graphic` tool as the app describes it; a refused call gets its error back for one retry. **Good** = built right on the first call; **recovered** = right after the retry; **bad** = wrong on screen or still refused.',
    '',
    '| Model | Good | Recovered | Bad | Usable | Right template | Facts on screen |',
    '| --- | ---: | ---: | ---: | ---: | ---: | ---: |',
  ];
  for (const [model, rows] of Object.entries(results)) {
    const n = (v: Row['verdict']) => rows.filter((r) => r.verdict === v).length;
    lines.push(`| ${model} | ${n('good')} | ${n('recovered')} | ${n('bad')} | ${pct(n('good') + n('recovered'), rows.length)} | ${pct(rows.filter((r) => r.templateOk).length, rows.length)} | ${pct(rows.filter((r) => r.factsShown).length, rows.length)} |`);
  }
  for (const [model, rows] of Object.entries(results)) {
    const bad = rows.filter((r) => r.verdict === 'bad' || !r.factsShown);
    if (!bad.length) continue;
    lines.push('', `## ${model}`, '');
    for (const r of bad) lines.push(`- **${r.brief.id}** (${r.template || 'no call'}): ${[...r.problems, ...(r.verdict !== 'bad' && !r.factsShown ? ['the request\'s facts are not all on screen'] : [])].join('; ') || 'ok'}`);
  }
  return `${lines.join('\n')}\n`;
}

const models = (process.env.LIVE_MODELS ?? '').split(',').map((m) => m.trim()).filter(Boolean);

describe('live small-model eval', () => {
  it.skipIf(!models.length)('calls the models and saves their calls', async () => {
    mkdirSync(CALLS_DIR, { recursive: true });
    const results: Record<string, Row[]> = {};
    await Promise.all(models.map(async (model) => {
      const calls: Call[] = [];
      const rows: Row[] = [];
      for (const brief of BRIEFS) {
        const attempts: Attempt[] = [];
        let reply = await ask(model, livePrompt(toolSpec, brief.request));
        attempts.push({ args: jsonFromReply(reply), reply: jsonFromReply(reply) ? undefined : reply.slice(-400) });
        let row = await score(brief, attempts, model);
        if (row.verdict === 'bad' && attempts[0].args) {
          const outcome = await runCase(liveCase(brief, attempts[0].args, model));
          const error = outcome.ok ? `The graphic built, but: ${row.problems.join('; ')}` : outcome.error ?? 'error';
          attempts[0].error = error;
          reply = await ask(model, livePrompt(toolSpec, brief.request, { args: attempts[0].args, error }));
          attempts.push({ args: jsonFromReply(reply), reply: jsonFromReply(reply) ? undefined : reply.slice(-400) });
          row = await score(brief, attempts, model);
        }
        calls.push({ brief: brief.id, attempts });
        rows.push(row);
      }
      writeFileSync(fileOf(model), `${JSON.stringify({ model, calls }, null, 1)}\n`);
      results[model] = rows;
    }));
    writeFileSync('docs/benchmarks/live-models.md', markdown(results));
    console.log(markdown(results));
  }, 3_600_000);

  it('replays the saved calls through the current tools', async () => {
    if (!existsSync(CALLS_DIR)) return;
    const results: Record<string, Row[]> = {};
    for (const file of readdirSync(CALLS_DIR).filter((f) => f.endsWith('.json'))) {
      const { model, calls } = JSON.parse(readFileSync(join(CALLS_DIR, file), 'utf8')) as { model: string; calls: Call[] };
      results[model] = [];
      for (const call of calls) {
        const brief = BRIEFS.find((b) => b.id === call.brief);
        if (brief) results[model].push(await score(brief, call.attempts, model));
      }
    }
    if (process.env.BENCH_WRITE) writeFileSync('docs/benchmarks/live-models-replay.md', markdown(results).replace('# Live small-model eval', '# Live small-model eval — saved calls replayed through the current tools'));
    for (const rows of Object.values(results)) expect(rows.length).toBe(BRIEFS.length);
  }, 120_000);
});
