// The marketplace's preview shelf: sample plugins shown while bhippi.com has no marketplace yet
// (or nothing is published), so the store never opens empty. Every one is marked `sample`, says
// "Coming soon", and can't be installed — they are ideas of what the store will hold, not listings.

import type { MarketPlugin } from './market';

export type SamplePlugin = MarketPlugin & { sample: true; icon: string; tagline: string; about: string; hue: number };

const sample = (item: Omit<SamplePlugin, 'sample' | 'author' | 'bhippi' | 'size' | 'updatedAt' | 'background' | 'publisher' | 'version'> & { author?: string }): SamplePlugin => ({
  author: 'Preview', bhippi: null, size: null, updatedAt: 0, background: false, publisher: null, version: null, ...item, sample: true,
});

/** `icon` is a lucide icon name (PluginMarket.tsx ICONS); `hue` colours its gradient tile. */
export const SAMPLE_PLUGINS: SamplePlugin[] = [
  sample({ id: 'sample-shot-list', name: 'Shot List Pro', tagline: 'Every clip, in order, one click away', summary: 'A living shot list of your timeline.', about: 'See every clip of the comp in timeline order with its track, start and length. Click a row to jump there. Stays in sync as you edit.', icon: 'ListVideo', hue: 262, category: 'utility', installs: 12400, rating: { average: 4.8, count: 312 }, permissions: { tools: [], network: [], chat: false } }),
  sample({ id: 'sample-captions', name: 'Caption Studio', tagline: 'Styled captions in seconds', summary: 'Word-by-word captions with 40 looks.', about: 'Turn speech into animated, styled captions and restyle them all at once.', icon: 'Subtitles', hue: 200, category: 'captions', installs: 9800, rating: { average: 4.7, count: 208 }, permissions: { tools: ['add_captions', 'set_caption_style'], network: [], chat: false } }),
  sample({ id: 'sample-beat-sync', name: 'Beat Sync', tagline: 'Cut on the beat, automatically', summary: 'Snaps your cuts to the music.', about: 'Finds the beats in your music bed and moves cuts onto them, with a strength slider.', icon: 'AudioWaveform', hue: 328, category: 'audio', installs: 7600, rating: { average: 4.6, count: 154 }, permissions: { tools: ['snap_cuts_to_beats'], network: [], chat: false } }),
  sample({ id: 'sample-color-match', name: 'Color Match', tagline: 'Make every shot feel like one film', summary: 'Matches the grade across clips.', about: 'Pick a hero shot; every other clip is graded to match it.', icon: 'Palette', hue: 18, category: 'editing', installs: 6900, rating: { average: 4.5, count: 121 }, permissions: { tools: ['color_grade'], network: [], chat: false } }),
  sample({ id: 'sample-silence', name: 'Silence Cutter', tagline: 'Tighten talking heads', summary: 'Removes dead air from speech.', about: 'Finds pauses in speech and removes them, with padding you choose.', icon: 'Scissors', hue: 140, category: 'editing', installs: 15100, rating: { average: 4.9, count: 402 }, permissions: { tools: ['remove_range'], network: [], chat: false } }),
  sample({ id: 'sample-kinetic', name: 'Kinetic Titles', tagline: 'Type that moves with intent', summary: '60 animated title presets.', about: 'Drop in animated titles that pick up your brand colours.', icon: 'Type', hue: 45, category: 'motion', installs: 5400, rating: { average: 4.6, count: 98 }, permissions: { tools: ['add_text', 'set_keyframes'], network: [], chat: false } }),
  sample({ id: 'sample-social', name: 'Social Export', tagline: 'Every aspect ratio at once', summary: 'Reels, Shorts and TikTok in one go.', about: 'Reframes your comp for vertical, square and wide, keeping faces in frame.', icon: 'Share2', hue: 190, category: 'integration', installs: 8200, rating: { average: 4.4, count: 176 }, permissions: { tools: ['create_comp', 'layout_clip'], network: [], chat: false } }),
  sample({ id: 'sample-meme-drop', name: 'Meme Drop', tagline: 'The right reaction, right on time', summary: 'Reaction clips and sounds on cue.', about: 'Suggests reaction moments and drops the meme or sound in place.', icon: 'Laugh', hue: 290, category: 'fun', installs: 11300, rating: { average: 4.7, count: 267 }, permissions: { tools: ['place_clip', 'place_sfx'], network: [], chat: true } }),
  sample({ id: 'sample-script', name: 'Script to Timeline', tagline: 'From script to first cut', summary: 'Lays out a rough cut from your script.', about: 'Paste a script; it places titles and markers for every scene so you can start cutting.', icon: 'FileText', hue: 225, category: 'automation', installs: 4300, rating: { average: 4.3, count: 71 }, permissions: { tools: ['add_marker', 'add_text'], network: [], chat: false } }),
  sample({ id: 'sample-loudness', name: 'Loudness Meter', tagline: 'Broadcast-ready sound', summary: 'LUFS metering and one-click levelling.', about: 'Watches your mix against YouTube, Spotify and broadcast targets and levels it for you.', icon: 'Gauge', hue: 160, category: 'audio', installs: 3900, rating: { average: 4.8, count: 64 }, permissions: { tools: ['level_audio'], network: [], chat: false } }),
  sample({ id: 'sample-brand-guard', name: 'Brand Guard', tagline: 'On-brand, every frame', summary: 'Flags off-brand fonts and colours.', about: 'Checks titles, colours and logos against your brand kit and fixes what drifts.', icon: 'ShieldCheck', hue: 250, category: 'utility', installs: 2800, rating: { average: 4.5, count: 43 }, permissions: { tools: ['apply_brand_kit'], network: [], chat: false } }),
  sample({ id: 'sample-board', name: 'Review Board', tagline: 'Send cuts to your team', summary: 'Share a cut, collect notes as markers.', about: 'Sends a review link to your team; their notes come back as timeline markers.', icon: 'SquareKanban', hue: 5, category: 'integration', installs: 3100, rating: { average: 4.2, count: 38 }, permissions: { tools: ['add_marker'], network: ['api.reviewboard.example'], chat: false } }),
];

export const isSample = (plugin: MarketPlugin): plugin is SamplePlugin => (plugin as Partial<SamplePlugin>).sample === true;
